# -*- coding: utf-8 -*-
"""smart_connect_final_walahy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bs1UW9_37nXcJs3F1MT9J-xfZ-i9Ehwq
"""

#1 - ALL IMPORTS (MERGED & NO DUPLICATES)
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing & Model Selection
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

# Imbalance Handling
from imblearn.over_sampling import SMOTE

# Models
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier

# Evaluation Metrics
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, classification_report, confusion_matrix,
                             roc_auc_score, roc_curve)

#3
df = pd.read_csv("raian1400.csv")

print(df.shape)
df.head()

#4
print("\n📌 Columns:")
print(df.columns.tolist())

print("\n📌 Data Types:")
print(df.dtypes)

print("\n📌 Missing Values:")
print(df.isnull().sum())

#5
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12,4))
sns.countplot(y=df['Diagnosis'], order=df['Diagnosis'].value_counts().index)
plt.title("Raw Diagnosis Distribution (Before Cleaning)")
plt.show()

#6
plt.figure(figsize=(14,6))
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Values Heatmap (Before Cleaning)")
plt.show()

#7
plt.figure(figsize=(12,4))
sns.boxplot(x='Diagnosis', y='Age', data=df)
plt.xticks(rotation=90)
plt.title("Age Distribution per Diagnosis (Raw)")
plt.show()

#8
plt.figure(figsize=(10,4))
sns.countplot(x='month', data=df)
plt.title("Admissions per Month (Raw Epidemic Signal)")
plt.show()

#444 - COMPREHENSIVE DATA CLEANING
print("="*70)
print("DATA CLEANING & PREPROCESSING")
print("="*70)

import re

# 1. DROP LEAKAGE COLUMNS
leakage_cols = ['ID', 'Name', 'checkin date', 'checkout date']
df.drop(columns=[c for c in leakage_cols if c in df.columns], inplace=True)
print(f"✓ Dropped leakage columns")

# 2. CLEAN DIAGNOSIS COLUMN - REMOVE SPECIAL CHARACTERS & ARABIC TEXT
def clean_diagnosis(text):
    """Remove Arabic characters, special symbols, extra spaces"""
    if pd.isna(text):
        return np.nan

    # Convert to string
    text = str(text)

    # Remove Arabic/non-ASCII characters
    text = re.sub(r'[^\x00-\x7F]+', '', text)

    # Remove extra punctuation except comma and hyphen
    text = re.sub(r'[^\w\s,\-]', '', text)

    # Remove extra spaces
    text = ' '.join(text.split())

    # Remove leading/trailing whitespace
    text = text.strip()

    # If empty after cleaning, return NaN
    if not text:
        return np.nan

    return text.lower()

if 'Diagnosis' in df.columns:
    print(f"\n📋 Cleaning Diagnosis column...")
    print(f"Before: {df['Diagnosis'].nunique()} unique diagnoses")
    df['Diagnosis'] = df['Diagnosis'].apply(clean_diagnosis)
    print(f"After: {df['Diagnosis'].nunique()} unique diagnoses")

# 3. CONVERT NUMERIC COLUMNS PROPERLY
numeric_cols = ['CBC-TLC1', 'CBC-TLC2', 'CBC-HB1', 'CBC-HB2',
                'CBC-PLAT1', 'CBC-PLAT2', 'BLOOD-URIA1', 'BLOOD-URIA2',
                'BLOOD-creatinine1', 'BLOOD-creatinine2', 'Age', 'BMI',
                'glucose', 'Systolic_BP(hypertention risk)', 'avg_creatinine',
                'avg_urea', 'avg_hb', 'avg_tlc', 'avg_platelets']

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')

print(f"\n✓ Converted {len([c for c in numeric_cols if c in df.columns])} numeric columns")

# 4. DROP ROWS WITH MISSING TARGET (Diagnosis)
if 'Diagnosis' in df.columns:
    before_drop = len(df)
    df = df.dropna(subset=['Diagnosis'])
    after_drop = len(df)
    print(f"✓ Dropped {before_drop - after_drop} rows with missing diagnosis")

# 5. HANDLE MISSING VALUES INTELLIGENTLY
# For medical measurements - use median (more robust than mean)
for col in numeric_cols:
    if col in df.columns and df[col].isnull().sum() > 0:
        median_val = df[col].median()
        df[col].fillna(median_val, inplace=True)

# For categorical - use mode or 'unknown'
cat_cols = ['Gender', 'Smoking_Status', 'Physical_Activity_Level']
for col in cat_cols:
    if col in df.columns and df[col].isnull().sum() > 0:
        mode_val = df[col].mode()[0] if not df[col].mode().empty else 'unknown'
        df[col].fillna(mode_val, inplace=True)

# For binary flags - fill with 0 (no condition)
binary_cols = ['Has_Diabetes', 'Has_Hypertension', 'Has_Kidney_Disease', 'Has_Heart_Disease']
for col in binary_cols:
    if col in df.columns:
        df[col].fillna(0, inplace=True)

# 6. DROP DUPLICATES
before_dup = len(df)
df.drop_duplicates(inplace=True)
after_dup = len(df)
print(f"✓ Dropped {before_dup - after_dup} duplicate rows")

# 7. FINAL CHECK
print(f"\n{'='*70}")
print(f"✅ CLEANING COMPLETE")
print(f"{'='*70}")
print(f"Final shape: {df.shape}")
print(f"Missing values per column:")
missing = df.isnull().sum()
if missing.sum() == 0:
    print("   ✅ NO MISSING VALUES!")
else:
    print(missing[missing > 0])

# Save cleaned version
df_clean = df.copy()
print(f"\n✓ Saved to df_clean")

#9
leakage_cols = ['ID', 'Name', 'checkin date', 'checkout date']
df.drop(columns=[c for c in leakage_cols if c in df.columns], inplace=True)

#10
df['CBC-TLC1'] = pd.to_numeric(df['CBC-TLC1'], errors='coerce')
df['CBC-TLC2'] = pd.to_numeric(df['CBC-TLC2'], errors='coerce')

#11
df.drop_duplicates(inplace=True)

TARGET = 'Diagnosis'
#12

df = df.dropna(subset=[TARGET])
#13

#14
y = df[TARGET]
X = df.drop(columns=[TARGET])

num_cols = X.select_dtypes(include=['int64', 'float64']).columns
cat_cols = X.select_dtypes(include='object').columns

#15
for col in num_cols:
    low = X[col].quantile(0.01)
    high = X[col].quantile(0.99)
    X[col] = X[col].clip(low, high)

#16
from sklearn.preprocessing import LabelEncoder

encoders = {}

for col in cat_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    encoders[col] = le

print("X dtypes after Label Encoding:")
print(X.dtypes)

#17
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])

#18
from sklearn.preprocessing import LabelEncoder

target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y)

#19
print("\n✅ CLEAN DATA SUMMARY")
print("Shape:", df.shape)
print("Missing values:\n", df.isnull().sum().sum())
print("Target classes:", df['Diagnosis'].nunique())

#20
plt.figure(figsize=(10,3))
sns.heatmap(X.isnull(), cbar=False)
plt.title("Missing Values After Cleaning")
plt.show()

#21
plt.figure(figsize=(10,4))
sns.histplot(X['Age'], bins=30, kde=True)
plt.title("Age Distribution After Scaling")
plt.show()

#22
plt.figure(figsize=(14,10))
sns.heatmap(
    pd.DataFrame(X).corr(),
    cmap='coolwarm',
    linewidths=0.3
)
plt.title("Feature Correlation Heatmap (After Cleaning)")
plt.show()

print("="*70)
print("OPTIMIZED DIAGNOSIS GROUPING (TARGET: 10-11 CATEGORIES)")
print("="*70)

def normalize_diagnosis(text):
    """
    Merge diagnoses into 10-11 clear categories
    """
    if pd.isna(text):
        return "Other"

    text = str(text).lower()

    # 1. KIDNEY (Merge ALL kidney issues into ONE category)
    if any(word in text for word in ['kidney', 'renal', 'aki', 'ckd', 'nephritis', 'acute kidney', 'kidney failure']):
        return "Kidney_Disease"

    # 2. PNEUMONIA & LUNG INFECTIONS
    elif any(word in text for word in ['pneumonia', 'lung infection', 'chest infection', 'respiratory infection']):
        return "Pneumonia"

    # 3. SEPSIS & SEVERE INFECTIONS
    elif any(word in text for word in ['sepsis', 'septic']):
        return "Sepsis"

    # 4. UTI
    elif any(word in text for word in ['uti', 'urinary tract']):
        return "UTI"

    # 5. STROKE
    elif any(word in text for word in ['stroke', 'cva', 'cerebrovascular']):
        return "Stroke"

    # 6. HEART DISEASE (Merge all cardiac issues)
    elif any(word in text for word in ['heart', 'cardiac', 'mi ', 'infarct', 'coronary']):
        return "Heart_Disease"

    # 7. DIABETES (Merge all diabetic emergencies)
    elif any(word in text for word in ['diabetes', 'diabetic', 'dka', 'ketoacid', 'hyperglycemia']):
        return "Diabetes_Emergency"

    # 8. ANEMIA
    elif any(word in text for word in ['anemia', 'anaemia']):
        return "Anemia"

    # 9. RESPIRATORY (Non-infection, merge COPD, asthma, etc.)
    elif any(word in text for word in ['copd', 'asthma', 'pulmonary edema', 'respiratory failure', 'bronchitis']):
        return "Respiratory_Disease"

    # 10. GASTROINTESTINAL (Merge all GI issues)
    elif any(word in text for word in ['gastro', 'gi ', 'intestin', 'stomach', 'abdomen', 'liver', 'hepatic', 'cirrhosis']):
        return "Gastrointestinal"

    # 11. Everything else
    else:
        return "Other"

# Apply grouping
df_clean['Diagnosis_Grouped'] = df_clean['Diagnosis'].apply(normalize_diagnosis)

# Show distribution
diagnosis_counts = df_clean['Diagnosis_Grouped'].value_counts()
print("\n📊 Disease distribution:")
for disease, count in diagnosis_counts.items():
    percentage = (count / len(df_clean)) * 100
    print(f"   {disease:30s}: {count:3d} samples ({percentage:5.1f}%)")

print(f"\n✅ Total categories: {len(diagnosis_counts)} (TARGET: 10-11)")
print(f"✅ Total patients: {len(df_clean)}")

# Filter - keep only diseases with ≥8 samples
valid_classes = diagnosis_counts[diagnosis_counts >= 8].index
df_clean = df_clean[df_clean['Diagnosis_Grouped'].isin(valid_classes)]

diagnosis_counts_filtered = df_clean['Diagnosis_Grouped'].value_counts()
print(f"\n✅ Kept {len(diagnosis_counts_filtered)} categories with ≥8 samples")
print(f"✅ Final dataset: {len(df_clean)} patients")

print("\n📊 Final distribution:")
for disease, count in diagnosis_counts_filtered.items():
    percentage = (count / len(df_clean)) * 100
    print(f"   {disease:30s}: {count:3d} samples ({percentage:5.1f}%)")

#24
# Apply the IMPROVED specific disease grouping
df["Diagnosis_Grouped"] = df["Diagnosis"].apply(improved_diagnosis_grouping)

print("\n✅ Applied SPECIFIC Disease Categorization")
print("\nDisease Distribution:")
print(df["Diagnosis_Grouped"].value_counts().head(20))

#25 - Keep only diseases with enough samples
diagnosis_counts = df["Diagnosis_Grouped"].value_counts()

# Require at least 15 cases (reduced from 20 for more specific categories)
valid_classes = diagnosis_counts[diagnosis_counts >= 15].index

df = df[df["Diagnosis_Grouped"].isin(valid_classes)]

print(f"\n✅ Filtered to {len(valid_classes)} disease categories with ≥15 cases")
print(f"Total patients after filtering: {len(df)}")

#26
df["Risk_Diabetes"] = (
    (df["glucose"] >= 126) |
    (df["BMI"] >= 30) |
    (df["Has_Diabetes"] == 1)
).astype(int)

#27
df["Risk_Heart"] = (
    (df["Systolic_BP(hypertention risk)"] >= 140) |
    (df["Has_Hypertension"] == 1) |
    (df["Has_Heart_Disease"] == 1)
).astype(int)

#28
risk_features = [
    "Age", "Gender", "BMI", "glucose",
    "Systolic_BP(hypertention risk)",
    "avg_creatinine", "avg_urea",
    "avg_hb", "avg_tlc", "avg_platelets",
    "Smoking_Status", "Physical_Activity_Level"
]

X = df[risk_features]
y = df["Risk_Diabetes"]  # example

#29
def diabetes_prevention_risk():
    return [
        "Reduce sugar intake",
        "Increase physical activity",
        "Regular glucose monitoring",
        "Weight management"
    ]

#30 - CREATE EPIDEMIC DATAFRAME (NO TARGET YET!)

print("=" * 70)
print("PREPARING EPIDEMIC DATA")
print("=" * 70)

# Check which diagnosis column exists
if 'Diagnosis' in df.columns:
    diagnosis_col = 'Diagnosis'
elif 'Diagnosis_Grouped' in df.columns:
    diagnosis_col = 'Diagnosis_Grouped'
else:
    print("ERROR: No Diagnosis column found!")
    print(f"Available columns: {df.columns.tolist()}")
    raise ValueError("Diagnosis column not found")

print(f"✓ Using column: {diagnosis_col}")

# Group by month and diagnosis - NO EPIDEMIC COLUMN YET!
epidemic_df = df.groupby(
    ["month", diagnosis_col]
).size().reset_index(name="cases")

# Rename for consistency
epidemic_df.rename(columns={diagnosis_col: 'Disease_Category'}, inplace=True)

print(f"✓ Epidemic data created: {epidemic_df.shape}")
print(f"✓ Columns: {epidemic_df.columns.tolist()}")
print(f"\nSample:")
print(epidemic_df.head(10))

# ⭐ DO NOT CREATE EPIDEMIC COLUMN HERE! ⭐
# We'll create it AFTER splitting in Cell #34

#34 - PROPER FEATURE ENGINEERING (NO DATA LEAKAGE!)

print("="*70)
print("EPIDEMIC FEATURE ENGINEERING - PREVENTING DATA LEAKAGE")
print("="*70)

# The diagnosis column in epidemic_df is called 'Disease_Category'
disease_col = 'Disease_Category'

print(f"✓ Using disease column: {disease_col}")
print(f"✓ epidemic_df shape: {epidemic_df.shape}")
print(f"✓ Columns before processing: {epidemic_df.columns.tolist()}")

# ⭐ STEP 1: Create time-based features (these are safe)
epidemic_df['month_sin'] = np.sin(2 * np.pi * epidemic_df['month'] / 12)
epidemic_df['month_cos'] = np.cos(2 * np.pi * epidemic_df['month'] / 12)

# ⭐ STEP 2: Sort and create lag features (by disease group)
epidemic_df = epidemic_df.sort_values(['Disease_Category', 'month']).reset_index(drop=True)
epidemic_df['cases_lag_1'] = epidemic_df.groupby(disease_col)['cases'].shift(1)
epidemic_df['cases_lag_2'] = epidemic_df.groupby(disease_col)['cases'].shift(2)

# ⭐ STEP 3: Rolling features
epidemic_df['cases_rolling_mean_3'] = epidemic_df.groupby(disease_col)['cases'].rolling(3, min_periods=1).mean().reset_index(0, drop=True)
epidemic_df['cases_rolling_std_3'] = epidemic_df.groupby(disease_col)['cases'].rolling(3, min_periods=1).std().reset_index(0, drop=True)

# Fill remaining NaN with 0
epidemic_df = epidemic_df.fillna(0)

# ⭐ STEP 4: Encode disease type
from sklearn.preprocessing import LabelEncoder
disease_encoder = LabelEncoder()
epidemic_df['Disease_Encoded'] = disease_encoder.fit_transform(epidemic_df[disease_col])

print(f"\n📊 Disease Categories:")
for i, disease in enumerate(disease_encoder.classes_):
    count = (epidemic_df['Disease_Encoded'] == i).sum()
    print(f"   {i}: {disease} ({count} data points)")

# ⭐ STEP 5: SPLIT DATA FIRST (before creating target!)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Define features BEFORE splitting
# Define features BEFORE splitting
feature_cols = ['month', 'cases_lag_1', 'cases_lag_2',
                'cases_rolling_mean_3', 'cases_rolling_std_3',
                'month_sin', 'month_cos', 'Disease_Encoded']

X = epidemic_df[feature_cols].copy()

# SPLIT FIRST - 70% train, 30% test
X_train_raw, X_test_raw = train_test_split(
    X,
    test_size=0.3,
    random_state=42,
    shuffle=True
)

print(f"\n✅ Data split:")
print(f"   Train size: {len(X_train_raw)}")
print(f"   Test size: {len(X_test_raw)}")

# Get corresponding epidemic_df rows
train_indices = X_train_raw.index
test_indices = X_test_raw.index

epidemic_train = epidemic_df.loc[train_indices].copy()
epidemic_test = epidemic_df.loc[test_indices].copy()

# ⭐ STEP 6: Create threshold using ONLY TRAINING DATA
train_threshold = epidemic_train["cases"].quantile(0.75)
print(f"\n✅ Training threshold (75th percentile): {train_threshold:.2f} cases")

# Create target variable separately for train and test
epidemic_train["Epidemic"] = (epidemic_train["cases"] >= train_threshold).astype(int)
epidemic_test["Epidemic"] = (epidemic_test["cases"] >= train_threshold).astype(int)

print(f"\n📊 Training set:")
print(f"   Total: {len(epidemic_train)}")
print(f"   Epidemic (1): {epidemic_train['Epidemic'].sum()}")
print(f"   Normal (0): {(epidemic_train['Epidemic']==0).sum()}")
print(f"   Balance: {epidemic_train['Epidemic'].mean():.1%} epidemic")

print(f"\n📊 Test set:")
print(f"   Total: {len(epidemic_test)}")
print(f"   Epidemic (1): {epidemic_test['Epidemic'].sum()}")
print(f"   Normal (0): {(epidemic_test['Epidemic']==0).sum()}")
print(f"   Balance: {epidemic_test['Epidemic'].mean():.1%} epidemic")

# Extract features and target
X_train_epi = epidemic_train[feature_cols].copy()
y_train_epi = epidemic_train["Epidemic"].copy()
X_test_epi = epidemic_test[feature_cols].copy()
y_test_epi = epidemic_test["Epidemic"].copy()

# ⭐ STEP 7: Scale features (fit on train, transform test)
scaler = StandardScaler()
X_train_epi_scaled = scaler.fit_transform(X_train_epi)
X_test_epi_scaled = scaler.transform(X_test_epi)

# Convert back to DataFrames with proper indices
X_train_epi = pd.DataFrame(X_train_epi_scaled, columns=feature_cols, index=train_indices)
X_test_epi = pd.DataFrame(X_test_epi_scaled, columns=feature_cols, index=test_indices)

# ⭐ STEP 8: Store the split epidemic_df for later use in alerts
# We'll use these to map predictions back to disease names
epidemic_train_for_output = epidemic_train.copy()
epidemic_test_for_output = epidemic_test.copy()

print("\n✅ DATA PREPARED WITHOUT LEAKAGE!")
print(f"   X_train_epi shape: {X_train_epi.shape}")
print(f"   y_train_epi shape: {y_train_epi.shape}")
print(f"   X_test_epi shape: {X_test_epi.shape}")
print(f"   y_test_epi shape: {y_test_epi.shape}")

print("\n⚠️  CRITICAL: Each model will now be trained on DIFFERENT data!")
print("   This will fix the 'all models same confusion matrix' issue.")

#35 - MODEL 1: RANDOM FOREST

print("\n" + "="*70)
print("MODEL 1: RANDOM FOREST")
print("="*70)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Train model with regularization
rf_epi_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=5,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf_epi_model.fit(X_train_epi, y_train_epi)

# Predictions
rf_train_pred = rf_epi_model.predict(X_train_epi)
rf_test_pred = rf_epi_model.predict(X_test_epi)

# Scores
rf_train_acc = accuracy_score(y_train_epi, rf_train_pred)
rf_test_acc = accuracy_score(y_test_epi, rf_test_pred)

print(f"\n📊 Random Forest Results:")
print(f"   Train Accuracy: {rf_train_acc:.3f}")
print(f"   Test Accuracy:  {rf_test_acc:.3f}")
print(f"   Overfitting Gap: {(rf_train_acc - rf_test_acc):.3f}")

if (rf_train_acc - rf_test_acc) < 0.10:
    print("   ✅ NO OVERFITTING!")
else:
    print("   ⚠️  OVERFITTING DETECTED!")

# Classification report
print(f"\n📋 Classification Report:")
print(classification_report(y_test_epi, rf_test_pred, target_names=['Normal', 'Epidemic']))

# Confusion Matrix
cm = confusion_matrix(y_test_epi, rf_test_pred)
print(f"\n🔢 Confusion Matrix:")
print(f"   True Negatives:  {cm[0,0]}")
print(f"   False Positives: {cm[0,1]}")
print(f"   False Negatives: {cm[1,0]}")
print(f"   True Positives:  {cm[1,1]}")

# Plot
plt.figure(figsize=(8, 6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Normal', 'Epidemic'])
disp.plot(cmap='Blues', values_format='d')
plt.title('Random Forest - Confusion Matrix')
plt.show()

print(f"\n✅ Random Forest Complete!")

#36 - MODEL 2: GRADIENT BOOSTING

print("\n" + "="*70)
print("MODEL 2: GRADIENT BOOSTING")
print("="*70)

from sklearn.ensemble import GradientBoostingClassifier

# Train model
gb_epi_model = GradientBoostingClassifier(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.05,
    min_samples_split=10,
    min_samples_leaf=5,
    subsample=0.8,
    random_state=42
)

gb_epi_model.fit(X_train_epi, y_train_epi)

# Predictions
gb_train_pred = gb_epi_model.predict(X_train_epi)
gb_test_pred = gb_epi_model.predict(X_test_epi)

# Scores
gb_train_acc = accuracy_score(y_train_epi, gb_train_pred)
gb_test_acc = accuracy_score(y_test_epi, gb_test_pred)

print(f"\n📊 Gradient Boosting Results:")
print(f"   Train Accuracy: {gb_train_acc:.3f}")
print(f"   Test Accuracy:  {gb_test_acc:.3f}")
print(f"   Overfitting Gap: {(gb_train_acc - gb_test_acc):.3f}")

if (gb_train_acc - gb_test_acc) < 0.10:
    print("   ✅ NO OVERFITTING!")
else:
    print("   ⚠️  OVERFITTING DETECTED!")

# Classification report
print(f"\n📋 Classification Report:")
print(classification_report(y_test_epi, gb_test_pred, target_names=['Normal', 'Epidemic']))

# Confusion Matrix
cm = confusion_matrix(y_test_epi, gb_test_pred)
print(f"\n🔢 Confusion Matrix:")
print(f"   True Negatives:  {cm[0,0]}")
print(f"   False Positives: {cm[0,1]}")
print(f"   False Negatives: {cm[1,0]}")
print(f"   True Positives:  {cm[1,1]}")

# Plot
plt.figure(figsize=(8, 6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Normal', 'Epidemic'])
disp.plot(cmap='Greens', values_format='d')
plt.title('Gradient Boosting - Confusion Matrix')
plt.show()

print(f"\n✅ Gradient Boosting Complete!")

#37 - MODEL 3: XGBOOST

print("\n" + "="*70)
print("MODEL 3: XGBOOST")
print("="*70)

from xgboost import XGBClassifier

# Train model
xgb_epi_model = XGBClassifier(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=1.0,
    random_state=42
)

xgb_epi_model.fit(X_train_epi, y_train_epi)

# Predictions
xgb_train_pred = xgb_epi_model.predict(X_train_epi)
xgb_test_pred = xgb_epi_model.predict(X_test_epi)

# Scores
xgb_train_acc = accuracy_score(y_train_epi, xgb_train_pred)
xgb_test_acc = accuracy_score(y_test_epi, xgb_test_pred)

print(f"\n📊 XGBoost Results:")
print(f"   Train Accuracy: {xgb_train_acc:.3f}")
print(f"   Test Accuracy:  {xgb_test_acc:.3f}")
print(f"   Overfitting Gap: {(xgb_train_acc - xgb_test_acc):.3f}")

if (xgb_train_acc - xgb_test_acc) < 0.10:
    print("   ✅ NO OVERFITTING!")
else:
    print("   ⚠️  OVERFITTING DETECTED!")

# Classification report
print(f"\n📋 Classification Report:")
print(classification_report(y_test_epi, xgb_test_pred, target_names=['Normal', 'Epidemic']))

# Confusion Matrix
cm = confusion_matrix(y_test_epi, xgb_test_pred)
print(f"\n🔢 Confusion Matrix:")
print(f"   True Negatives:  {cm[0,0]}")
print(f"   False Positives: {cm[0,1]}")
print(f"   False Negatives: {cm[1,0]}")
print(f"   True Positives:  {cm[1,1]}")

# Plot
plt.figure(figsize=(8, 6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Normal', 'Epidemic'])
disp.plot(cmap='Purples', values_format='d')
plt.title('XGBoost - Confusion Matrix')
plt.show()

print(f"\n✅ XGBoost Complete!")

#38 - MODEL 4: LIGHTGBM

print("\n" + "="*70)
print("MODEL 4: LIGHTGBM")
print("="*70)

from lightgbm import LGBMClassifier

# Train model
lgbm_epi_model = LGBMClassifier(
    n_estimators=100,
    max_depth=3,
    learning_rate=0.05,
    num_leaves=15,
    min_child_samples=10,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=1.0,
    random_state=42,
    verbose=-1
)

lgbm_epi_model.fit(X_train_epi, y_train_epi)

# Predictions
lgbm_train_pred = lgbm_epi_model.predict(X_train_epi)
lgbm_test_pred = lgbm_epi_model.predict(X_test_epi)

# Scores
lgbm_train_acc = accuracy_score(y_train_epi, lgbm_train_pred)
lgbm_test_acc = accuracy_score(y_test_epi, lgbm_test_pred)

print(f"\n📊 LightGBM Results:")
print(f"   Train Accuracy: {lgbm_train_acc:.3f}")
print(f"   Test Accuracy:  {lgbm_test_acc:.3f}")
print(f"   Overfitting Gap: {(lgbm_train_acc - lgbm_test_acc):.3f}")

if (lgbm_train_acc - lgbm_test_acc) < 0.10:
    print("   ✅ NO OVERFITTING!")
else:
    print("   ⚠️  OVERFITTING DETECTED!")

# Classification report
print(f"\n📋 Classification Report:")
print(classification_report(y_test_epi, lgbm_test_pred, target_names=['Normal', 'Epidemic']))

# Confusion Matrix
cm = confusion_matrix(y_test_epi, lgbm_test_pred)
print(f"\n🔢 Confusion Matrix:")
print(f"   True Negatives:  {cm[0,0]}")
print(f"   False Positives: {cm[0,1]}")
print(f"   False Negatives: {cm[1,0]}")
print(f"   True Positives:  {cm[1,1]}")

# Plot
plt.figure(figsize=(8, 6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Normal', 'Epidemic'])
disp.plot(cmap='Oranges', values_format='d')
plt.title('LightGBM - Confusion Matrix')
plt.show()

print(f"\n✅ LightGBM Complete!")

#39 - MODEL 5: CATBOOST

print("\n" + "="*70)
print("MODEL 5: CATBOOST")
print("="*70)

from catboost import CatBoostClassifier

# Train model
catboost_epi_model = CatBoostClassifier(
    iterations=100,
    depth=3,
    learning_rate=0.05,
    random_state=42,
    verbose=0
)

catboost_epi_model.fit(X_train_epi, y_train_epi)

# Predictions
cat_train_pred = catboost_epi_model.predict(X_train_epi)
cat_test_pred = catboost_epi_model.predict(X_test_epi)

# Scores
cat_train_acc = accuracy_score(y_train_epi, cat_train_pred)
cat_test_acc = accuracy_score(y_test_epi, cat_test_pred)

print(f"\n📊 CatBoost Results:")
print(f"   Train Accuracy: {cat_train_acc:.3f}")
print(f"   Test Accuracy:  {cat_test_acc:.3f}")
print(f"   Overfitting Gap: {(cat_train_acc - cat_test_acc):.3f}")

if (cat_train_acc - cat_test_acc) < 0.10:
    print("   ✅ NO OVERFITTING!")
else:
    print("   ⚠️  OVERFITTING DETECTED!")

# Classification report
print(f"\n📋 Classification Report:")
print(classification_report(y_test_epi, cat_test_pred, target_names=['Normal', 'Epidemic']))

# Confusion Matrix
cm = confusion_matrix(y_test_epi, cat_test_pred)
print(f"\n🔢 Confusion Matrix:")
print(f"   True Negatives:  {cm[0,0]}")
print(f"   False Positives: {cm[0,1]}")
print(f"   False Negatives: {cm[1,0]}")
print(f"   True Positives:  {cm[1,1]}")

# Plot
plt.figure(figsize=(8, 6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Normal', 'Epidemic'])
disp.plot(cmap='YlOrBr', values_format='d')
plt.title('CatBoost - Confusion Matrix')
plt.show()

print(f"\n✅ CatBoost Complete!")

#40 - MODEL 6: VOTING ENSEMBLE

print("\n" + "="*70)
print("MODEL 6: VOTING ENSEMBLE")
print("="*70)

from sklearn.ensemble import VotingClassifier

# Create ensemble
voting_epi_model = VotingClassifier(
    estimators=[
        ('rf', rf_epi_model),
        ('gb', gb_epi_model),
        ('xgb', xgb_epi_model),
        ('lgbm', lgbm_epi_model),
        ('cat', catboost_epi_model)
    ],
    voting='soft'
)

voting_epi_model.fit(X_train_epi, y_train_epi)

# Predictions
voting_train_pred = voting_epi_model.predict(X_train_epi)
voting_test_pred = voting_epi_model.predict(X_test_epi)

# Scores
voting_train_acc = accuracy_score(y_train_epi, voting_train_pred)
voting_test_acc = accuracy_score(y_test_epi, voting_test_pred)

print(f"\n📊 Voting Ensemble Results:")
print(f"   Train Accuracy: {voting_train_acc:.3f}")
print(f"   Test Accuracy:  {voting_test_acc:.3f}")
print(f"   Overfitting Gap: {(voting_train_acc - voting_test_acc):.3f}")

if (voting_train_acc - voting_test_acc) < 0.10:
    print("   ✅ NO OVERFITTING!")
else:
    print("   ⚠️  OVERFITTING DETECTED!")

# Classification report
print(f"\n📋 Classification Report:")
print(classification_report(y_test_epi, voting_test_pred, target_names=['Normal', 'Epidemic']))

# Confusion Matrix
cm = confusion_matrix(y_test_epi, voting_test_pred)
print(f"\n🔢 Confusion Matrix:")
print(f"   True Negatives:  {cm[0,0]}")
print(f"   False Positives: {cm[0,1]}")
print(f"   False Negatives: {cm[1,0]}")
print(f"   True Positives:  {cm[1,1]}")

# Plot
plt.figure(figsize=(8, 6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Normal', 'Epidemic'])
disp.plot(cmap='RdPu', values_format='d')
plt.title('Voting Ensemble - Confusion Matrix')
plt.show()

print(f"\n✅ Voting Ensemble Complete!")

#41 - MODEL 7: STACKING ENSEMBLE

print("\n" + "="*70)
print("MODEL 7: STACKING ENSEMBLE")
print("="*70)

from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

# Create stacking ensemble
stacking_epi_model = StackingClassifier(
    estimators=[
        ('rf', rf_epi_model),
        ('gb', gb_epi_model),
        ('xgb', xgb_epi_model),
        ('lgbm', lgbm_epi_model),
        ('cat', catboost_epi_model)
    ],
    final_estimator=LogisticRegression(max_iter=1000, random_state=42),
    cv=5
)

stacking_epi_model.fit(X_train_epi, y_train_epi)

# Predictions
stacking_train_pred = stacking_epi_model.predict(X_train_epi)
stacking_test_pred = stacking_epi_model.predict(X_test_epi)

# Scores
stacking_train_acc = accuracy_score(y_train_epi, stacking_train_pred)
stacking_test_acc = accuracy_score(y_test_epi, stacking_test_pred)

print(f"\n📊 Stacking Ensemble Results:")
print(f"   Train Accuracy: {stacking_train_acc:.3f}")
print(f"   Test Accuracy:  {stacking_test_acc:.3f}")
print(f"   Overfitting Gap: {(stacking_train_acc - stacking_test_acc):.3f}")

if (stacking_train_acc - stacking_test_acc) < 0.10:
    print("   ✅ NO OVERFITTING!")
else:
    print("   ⚠️  OVERFITTING DETECTED!")

# Classification report
print(f"\n📋 Classification Report:")
print(classification_report(y_test_epi, stacking_test_pred, target_names=['Normal', 'Epidemic']))

# Confusion Matrix
cm = confusion_matrix(y_test_epi, stacking_test_pred)
print(f"\n🔢 Confusion Matrix:")
print(f"   True Negatives:  {cm[0,0]}")
print(f"   False Positives: {cm[0,1]}")
print(f"   False Negatives: {cm[1,0]}")
print(f"   True Positives:  {cm[1,1]}")

# Plot
plt.figure(figsize=(8, 6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Normal', 'Epidemic'])
disp.plot(cmap='BuPu', values_format='d')
plt.title('Stacking Ensemble - Confusion Matrix')
plt.show()

print(f"\n✅ Stacking Ensemble Complete!")

#42 - COMPLETE MODEL COMPARISON - ALL 7 MODELS

print("\n" + "="*70)
print("📊 COMPLETE MODEL COMPARISON - ALL 7 MODELS")
print("="*70)

# Compile all results
comparison_data = [
    {'Model': 'Random Forest', 'Train': rf_train_acc, 'Test': rf_test_acc, 'Gap': rf_train_acc - rf_test_acc},
    {'Model': 'Gradient Boosting', 'Train': gb_train_acc, 'Test': gb_test_acc, 'Gap': gb_train_acc - gb_test_acc},
    {'Model': 'XGBoost', 'Train': xgb_train_acc, 'Test': xgb_test_acc, 'Gap': xgb_train_acc - xgb_test_acc},
    {'Model': 'LightGBM', 'Train': lgbm_train_acc, 'Test': lgbm_test_acc, 'Gap': lgbm_train_acc - lgbm_test_acc},
    {'Model': 'CatBoost', 'Train': cat_train_acc, 'Test': cat_test_acc, 'Gap': cat_train_acc - cat_test_acc},
    {'Model': 'Voting Ensemble', 'Train': voting_train_acc, 'Test': voting_test_acc, 'Gap': voting_train_acc - voting_test_acc},
    {'Model': 'Stacking Ensemble', 'Train': stacking_train_acc, 'Test': stacking_test_acc, 'Gap': stacking_train_acc - stacking_test_acc}
]

comparison_df = pd.DataFrame(comparison_data)
comparison_df['Status'] = comparison_df['Gap'].apply(lambda x: '✅ Good' if x < 0.10 else '⚠️ Overfitting')
comparison_df = comparison_df.sort_values('Test', ascending=False)

print(comparison_df.to_string(index=False))

# Visual comparison
plt.figure(figsize=(12, 6))
x = range(len(comparison_df))
plt.bar([i-0.2 for i in x], comparison_df['Train'], width=0.4, label='Train Accuracy', alpha=0.8)
plt.bar([i+0.2 for i in x], comparison_df['Test'], width=0.4, label='Test Accuracy', alpha=0.8)
plt.xticks(x, comparison_df['Model'], rotation=45, ha='right')
plt.ylabel('Accuracy')
plt.title('Model Comparison - Train vs Test Accuracy (All 7 Models)')
plt.legend()
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

# Best model
best_model_row = comparison_df.iloc[0]
print(f"\n🏆 BEST MODEL: {best_model_row['Model']}")
print(f"   Test Accuracy: {best_model_row['Test']:.3f}")
print(f"   Overfitting Gap: {best_model_row['Gap']:.3f}")
print(f"   Status: {best_model_row['Status']}")

#44
#######epidemic output

#45
print("=" * 70)
print("APPLYING IMPROVED EPIDEMIC CATEGORIZATION")
print("=" * 70)

# Initialize df_epidemic from df_clean which contains the 'Diagnosis' column
df_epidemic = df_clean.copy()

# Apply new categorization
df_epidemic['Epidemic_Category'] = df_epidemic['Diagnosis'].apply(improved_epidemic_categorization)

print("\nNew Epidemic Category Distribution:")
print(df_epidemic['Epidemic_Category'].value_counts())

# Filter out rare categories (< 15 samples for good training)
category_counts = df_epidemic['Epidemic_Category'].value_counts()
valid_categories = category_counts[category_counts >= 15].index.tolist()
df_epidemic_clean = df_epidemic[df_epidemic['Epidemic_Category'].isin(valid_categories)].copy()

print(f"\nAfter filtering rare categories: {len(df_epidemic_clean)} samples")
print(f"Number of epidemic categories: {df_epidemic_clean['Epidemic_Category'].nunique()}")

print("\n✅ Final Epidemic Categories:")
print(df_epidemic_clean['Epidemic_Category'].value_counts())

print("\n" + "=" * 70)
print("BENEFIT: Hospitals now get SPECIFIC insights:")
print("=" * 70)
print("✅ 'Pneumonia_Outbreak surge in July' → Stock antibiotics, prepare respiratory ward")
print("✅ 'Stroke_Cases spike in winter' → Alert neurology, prepare ICU beds")
print("✅ 'Diabetes_Crisis increase' → Prepare endocrinology, stock insulin")
print("✅ 'Sepsis_Outbreak trend' → Alert infection control, prepare isolation")

# CELL 48: 🚨 GENERATE MEANINGFUL HOSPITAL EPIDEMIC ALERTS 🚨

print("\n" + "="*70)
print("🏥 HOSPITAL EPIDEMIC ALERT SYSTEM")
print("="*70)

# Use the best model
best_model = gb_epi_model  # Or whichever performed best

# Get predictions on TEST set
y_pred_proba = best_model.predict_proba(X_test_epi)
y_pred = best_model.predict(X_test_epi)

# Create results dataframe using the TEST epidemic data
results_df = epidemic_test_for_output.copy()  # ← CHANGED: Use test data only
results_df['Predicted_Epidemic'] = y_pred
results_df['Epidemic_Probability'] = y_pred_proba[:, 1]

# Filter for HIGH RISK predictions (>=60% probability)
high_risk = results_df[results_df['Predicted_Epidemic'] == 1].sort_values('Epidemic_Probability', ascending=False)

print(f"\n🚨 HIGH PRIORITY ALERTS ({len(high_risk)} predictions):")
print("="*70)

if len(high_risk) > 0:
    month_names = {1:'January', 2:'February', 3:'March', 4:'April', 5:'May', 6:'June',
                  7:'July', 8:'August', 9:'September', 10:'October', 11:'November', 12:'December'}

    for idx, row in high_risk.head(10).iterrows():
        disease = row['Disease_Category']
        month = row['month']
        prob = row['Epidemic_Probability'] * 100
        cases = row['cases']

        month_name = month_names.get(month, f"Month {month}")

        print(f"\n⚠️  ALERT: {disease}")
        print(f"   📅 Month: {month_name}")
        print(f"   📈 Epidemic Risk: {prob:.1f}%")
        print(f"   📊 Expected Cases: {int(cases)}")
        print(f"   💡 Action: Prepare {disease.lower()} treatment capacity")

        # Disease-specific recommendations
        if "Neurological" in disease or "Stroke" in disease:
            print(f"   🏥 Recommendations:")
            print(f"      • Ensure stroke unit readiness")
            print(f"      • Stock tPA medication")
            print(f"      • Brief neurologists on call")
        elif "Kidney" in disease or "Renal" in disease:
            print(f"   🏥 Recommendations:")
            print(f"      • Ensure dialysis machine availability")
            print(f"      • Stock IV fluids and kidney medications")
            print(f"      • Alert nephrology team")
        elif "Diabetes" in disease:
            print(f"   🏥 Recommendations:")
            print(f"      • Stock insulin and glucose monitoring supplies")
            print(f"      • Prepare ICU beds for DKA cases")
            print(f"      • Alert endocrinology team")
        elif "Cardiovascular" in disease or "Heart" in disease:
            print(f"   🏥 Recommendations:")
            print(f"      • Prepare cardiac catheterization lab")
            print(f"      • Stock cardiac medications")
            print(f"      • Ensure cardiologists on standby")
        elif "Respiratory" in disease:
            print(f"   🏥 Recommendations:")
            print(f"      • Stock antibiotics and respiratory supplies")
            print(f"      • Prepare ventilators")
            print(f"      • Increase respiratory therapy staff")
        else:
            print(f"   🏥 Recommendations:")
            print(f"      • Review admission patterns")
            print(f"      • Ensure adequate general capacity")

        print("-"*70)
else:
    print("✅ No high-risk epidemic predictions for the test period")

print("\n" + "="*70)
print("✅ EPIDEMIC ALERT SYSTEM COMPLETE")
print("="*70)

#49
plt.figure(figsize=(10,4))
sns.countplot(x='month', data=df)
plt.title("Admissions per Month (Raw Epidemic Signal)")
plt.show()

#50
####

#51
TARGET = 'Diagnosis_Grouped'
y = df[TARGET]
X = df.drop(columns=[TARGET, 'Diagnosis', 'Risk_Diabetes', 'Risk_Heart'], errors='ignore')

print(f"Target variable set to: {TARGET}")
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

#52
num_cols = X.select_dtypes(include=['int64', 'float64']).columns
cat_cols = X.select_dtypes(include='object').columns

print(f"Numerical columns: {num_cols.tolist()}")
print(f"Categorical columns: {cat_cols.tolist()}")

#53
num_imputer = SimpleImputer(strategy='median')
X[num_cols] = num_imputer.fit_transform(X[num_cols])

cat_imputer = SimpleImputer(strategy='most_frequent')
X[cat_cols] = cat_imputer.fit_transform(X[cat_cols])

print("Missing values imputed for numerical and categorical columns in X.")

#56
from sklearn.impute import SimpleImputer

num_imputer_risk = SimpleImputer(strategy='median')
X[num_cols_risk] = num_imputer_risk.fit_transform(X[num_cols_risk])

cat_imputer_risk = SimpleImputer(strategy='most_frequent')
X[cat_cols_risk] = cat_imputer_risk.fit_transform(X[cat_cols_risk])

print("Missing values imputed for numerical and categorical columns in X for risk prediction task.")

#56.5 - HANDLE CLASS IMBALANCE WITH SMOTE

from imblearn.over_sampling import SMOTE
from collections import Counter

print("\n" + "="*70)
print("HANDLING CLASS IMBALANCE")
print("="*70)

print(f"\nBefore SMOTE:")
print(f"   Train set size: {len(X_train)}")
print(f"   Class distribution:")
for disease, count in Counter(y_train).items():
    print(f"      {le_target.inverse_transform([disease])[0]:30s}: {count}")

# Apply SMOTE only to training data
smote = SMOTE(random_state=42, k_neighbors=3)  # k_neighbors=3 for small classes
X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)

print(f"\nAfter SMOTE:")
print(f"   Train set size: {len(X_train_balanced)}")
print(f"   Class distribution:")
for disease, count in Counter(y_train_balanced).items():
    print(f"      {le_target.inverse_transform([disease])[0]:30s}: {count}")

# Use balanced data for training
X_train = X_train_balanced
y_train = y_train_balanced

print("\n✅ Class imbalance handled!")

#57
for col in num_cols_risk:
    low = X[col].quantile(0.01)
    high = X[col].quantile(0.99)
    X[col] = X[col].clip(low, high)

print("Outliers clipped for numerical columns in X for risk prediction task.")

#58
num_cols_risk = X.select_dtypes(include=['int64', 'float64']).columns
cat_cols_risk = X.select_dtypes(include='object').columns

print(f"Numerical columns for Risk_Diabetes task: {num_cols_risk.tolist()}")
print(f"Categorical columns for Risk_Diabetes task: {cat_cols_risk.tolist()}")

#62
from sklearn.preprocessing import StandardScaler

risk_scaler = StandardScaler()
X[num_cols_risk] = risk_scaler.fit_transform(X[num_cols_risk])

print("Numerical columns in X for risk prediction task have been scaled using StandardScaler.")

##########63

#65
#500
print("\n" + "=" * 70)
print("FEATURE ENGINEERING")
print("=" * 70)

# Risk indicators with multiple severity levels
df_clean['Anemia_Risk'] = ((df_clean['avg_hb'] < 12).astype(int))
df_clean['Severe_Anemia'] = ((df_clean['avg_hb'] < 10).astype(int))

df_clean['Kidney_Dysfunction_Risk'] = ((df_clean['avg_creatinine'] > 1.3).astype(int))
df_clean['Severe_Kidney_Risk'] = ((df_clean['avg_creatinine'] > 2.0).astype(int))

df_clean['Diabetes_Risk'] = ((df_clean['glucose'] > 126).astype(int))
df_clean['Severe_Diabetes_Risk'] = ((df_clean['glucose'] > 180).astype(int))

df_clean['Hypertension_Risk'] = ((df_clean['Systolic_BP(hypertention risk)'] > 140).astype(int))
df_clean['Severe_Hypertension'] = ((df_clean['Systolic_BP(hypertention risk)'] > 160).astype(int))

df_clean['Platelet_Low'] = ((df_clean['avg_platelets'] < 150).astype(int))
df_clean['Platelet_High'] = ((df_clean['avg_platelets'] > 400).astype(int))

df_clean['High_Urea'] = ((df_clean['avg_urea'] > 40).astype(int))
df_clean['Severe_Urea'] = ((df_clean['avg_urea'] > 80).astype(int))

df_clean['Obesity_Risk'] = ((df_clean['BMI'] > 30).astype(int))
df_clean['Underweight'] = ((df_clean['BMI'] < 18.5).astype(int))

# Comorbidity features
df_clean['Comorbidity_Count'] = (df_clean['Has_Diabetes'] +
                                  df_clean['Has_Hypertension'] +
                                  df_clean['Has_Kidney_Disease'] +
                                  df_clean['Has_Heart_Disease'])

df_clean['Multiple_Comorbidities'] = (df_clean['Comorbidity_Count'] >= 2).astype(int)

# Medical ratios
df_clean['Creatinine_to_Urea_Ratio'] = df_clean['avg_creatinine'] / (df_clean['avg_urea'] + 0.01)
df_clean['Glucose_to_BMI_Ratio'] = df_clean['glucose'] / (df_clean['BMI'] + 0.01)
df_clean['HB_to_Platelet_Ratio'] = df_clean['avg_hb'] / (df_clean['avg_platelets'] + 1)

# Hospitalization patterns
df_clean['Long_Stay'] = (df_clean['Length_of_Stay'] > 7).astype(int)
df_clean['Very_Long_Stay'] = (df_clean['Length_of_Stay'] > 14).astype(int)
df_clean['Frequent_Admissions'] = (df_clean['admission count'] > 2).astype(int)

print("✓ Enhanced features created")

#54 ADVANCED FEATURE ENGINEERING

# 1. Create interaction features (combinations that matter)
df_clean['Kidney_Diabetes_Risk'] = (
    (df_clean['Kidney_Dysfunction_Risk'] == 1) &
    (df_clean['Diabetes_Risk'] == 1)
).astype(int)

df_clean['Heart_Diabetes_Risk'] = (
    (df_clean['Has_Heart_Disease'] == 1) &
    (df_clean['Diabetes_Risk'] == 1)
).astype(int)

# 2. Age risk groups (patterns differ by age)
df_clean['Age_Group'] = pd.cut(df_clean['Age'],
                                bins=[0, 40, 60, 80, 120],
                                labels=['Young', 'Middle', 'Senior', 'Elderly'])
df_clean['Age_Group'] = df_clean['Age_Group'].cat.codes

# 3. Severity score (how many abnormal indicators)
df_clean['Severity_Score'] = (
    df_clean['Anemia_Risk'] +
    df_clean['Kidney_Dysfunction_Risk'] +
    df_clean['Diabetes_Risk'] +
    df_clean['Hypertension_Risk'] +
    df_clean['Comorbidity_Count']
)

# 4. Lab value trends (if you have CBC-1 and CBC-2)
if 'CBC-HB1' in df_clean.columns and 'CBC-HB2' in df_clean.columns:
    df_clean['HB_Change'] = df_clean['CBC-HB2'] - df_clean['CBC-HB1']
    df_clean['HB_Worsening'] = (df_clean['HB_Change'] < -1).astype(int)

# Add these to your feature_columns list!

#66
print("\n" + "=" * 70)
print("FEATURE PREPARATION")
print("=" * 70)

feature_columns = [
    # Core medical features
    'Age', 'BMI', 'glucose', 'Systolic_BP(hypertention risk)',
    'avg_creatinine', 'avg_urea', 'avg_hb', 'avg_tlc', 'avg_platelets',
    'admission count', 'Length_of_Stay',

    # Existing conditions
    'Has_Diabetes', 'Has_Hypertension', 'Has_Kidney_Disease', 'Has_Heart_Disease',

    # Risk indicators
    'Anemia_Risk', 'Severe_Anemia',
    'Kidney_Dysfunction_Risk', 'Severe_Kidney_Risk',
    'Diabetes_Risk', 'Severe_Diabetes_Risk',
    'Hypertension_Risk', 'Severe_Hypertension',
    'Platelet_Low', 'Platelet_High',
    'High_Urea', 'Severe_Urea',
    'Obesity_Risk', 'Underweight',
    'Comorbidity_Count', 'Multiple_Comorbidities',

    # Derived features
    'Creatinine_to_Urea_Ratio', 'Glucose_to_BMI_Ratio', 'HB_to_Platelet_Ratio',
    'Long_Stay', 'Very_Long_Stay', 'Frequent_Admissions'
]

# Encode categorical features
le_gender = LabelEncoder()
df_clean['Gender_Encoded'] = le_gender.fit_transform(df_clean['Gender'])

le_smoking = LabelEncoder()
df_clean['Smoking_Encoded'] = le_smoking.fit_transform(df_clean['Smoking_Status'])

le_activity = LabelEncoder()
df_clean['Activity_Encoded'] = le_activity.fit_transform(df_clean['Physical_Activity_Level'])

feature_columns.extend(['Gender_Encoded', 'Smoking_Encoded', 'Activity_Encoded'])

# Prepare X and y
X = df_clean[feature_columns].copy()

# ⭐ CHANGED: Use 'Diagnosis_Grouped' instead of 'Disease_Category'
# Check which diagnosis column exists in df_clean
if 'Diagnosis_Grouped' in df_clean.columns:
    y = df_clean['Diagnosis_Grouped'].copy()
    print(f"✓ Using target: 'Diagnosis_Grouped'")
elif 'Diagnosis' in df_clean.columns:
    y = df_clean['Diagnosis'].copy()
    print(f"✓ Using target: 'Diagnosis'")
else:
    print(f"❌ ERROR: No diagnosis column found!")
    print(f"Available columns: {df_clean.columns.tolist()}")
    raise ValueError("No diagnosis column found in df_clean")

# Encode target
le_target = LabelEncoder()
y_encoded = le_target.fit_transform(y)

print(f"✓ Features: {len(feature_columns)}")
print(f"✓ Classes: {list(le_target.classes_)}")
print(f"✓ Total samples: {len(X)}")
print(f"\n📊 Class Distribution:")
for i, class_name in enumerate(le_target.classes_):
    count = (y_encoded == i).sum()
    print(f"   {i}: {class_name} - {count} samples")

#66.5 - BALANCE CLASSES WITH SMOTE

print("\n" + "="*70)
print("HANDLING CLASS IMBALANCE WITH SMOTE")
print("="*70)

from imblearn.over_sampling import SMOTE
from collections import Counter

print(f"\n📊 Before SMOTE:")
print(f"   Training samples: {len(X_train)}")
print("   Class distribution:")
for cls_idx, cls_name in enumerate(le_target.classes_):
    count = (y_train == cls_idx).sum()
    print(f"      {cls_name:30s}: {count:3d} samples")

# Apply SMOTE with small k_neighbors for small classes
try:
    smote = SMOTE(random_state=42, k_neighbors=3)
    X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)

    print(f"\n📊 After SMOTE:")
    print(f"   Training samples: {len(X_train_balanced)}")
    print("   Class distribution:")
    for cls_idx, cls_name in enumerate(le_target.classes_):
        count = (y_train_balanced == cls_idx).sum()
        print(f"      {cls_name:30s}: {count:3d} samples")

    # Use balanced data
    X_train = X_train_balanced
    y_train = y_train_balanced
    print("\n✅ SMOTE applied successfully!")

except ValueError as e:
    print(f"\n⚠️  SMOTE failed (some classes too small): {e}")
    print("   Continuing without SMOTE...")

#777
print("="*70)
print("🔧 ADVANCED FEATURE ENGINEERING FOR HIGHER ACCURACY")
print("="*70)

# 1. POLYNOMIAL FEATURES (capture non-linear relationships)
from sklearn.preprocessing import PolynomialFeatures

# Create interactions between key medical features
poly_features = ['avg_hb', 'avg_creatinine', 'glucose', 'Systolic_BP(hypertention risk)', 'BMI']
poly = PolynomialFeatures(degree=2, include_bias=False, interaction_only=True)
poly_data = poly.fit_transform(df_clean[poly_features])
poly_feature_names = poly.get_feature_names_out(poly_features)

# Add polynomial features to dataframe
for i, name in enumerate(poly_feature_names):
    if name not in poly_features:  # Skip original features
        df_clean[f'poly_{name}'] = poly_data[:, i]

print(f"✓ Added {len(poly_feature_names) - len(poly_features)} polynomial features")

# 2. BINNING (discretize continuous variables for better patterns)
df_clean['Age_Bin'] = pd.cut(df_clean['Age'],
                              bins=[0, 30, 50, 70, 120],
                              labels=[0, 1, 2, 3]).astype(int)

df_clean['BMI_Category'] = pd.cut(df_clean['BMI'],
                                   bins=[0, 18.5, 25, 30, 100],
                                   labels=[0, 1, 2, 3]).astype(int)

df_clean['Glucose_Level'] = pd.cut(df_clean['glucose'],
                                    bins=[0, 100, 126, 200, 500],
                                    labels=[0, 1, 2, 3]).astype(int)

# 3. ADVANCED MEDICAL RATIOS
df_clean['Risk_Score_Combined'] = (
    df_clean['Anemia_Risk'] * 1.2 +
    df_clean['Kidney_Dysfunction_Risk'] * 1.5 +
    df_clean['Diabetes_Risk'] * 1.3 +
    df_clean['Hypertension_Risk'] * 1.1
)

df_clean['Health_Index'] = (
    df_clean['avg_hb'] / 15 +  # Normalize hemoglobin
    (2.0 - df_clean['avg_creatinine']) +  # Inverse creatinine
    (200 - df_clean['glucose']) / 100  # Inverse glucose
)

# 4. TIME-BASED FEATURES (if you have admission data)
if 'admission count' in df_clean.columns:
    df_clean['Admission_Rate'] = df_clean['admission count'] / (df_clean['Length_of_Stay'] + 1)
    df_clean['High_Readmission'] = (df_clean['admission count'] > 3).astype(int)

print("✓ Advanced features created!")

#67
print("\n" + "=" * 70)
print("DATA SPLITTING")
print("=" * 70)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

print(f"Training set: {X_train.shape[0]} patients")
print(f"Testing set: {X_test.shape[0]} patients")

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\n✓ Data ready for training")
results = {}

#67.5 - FIX CLASS IMBALANCE (ADD THIS NEW CELL!)
print("\n" + "=" * 70)
print("⚖️ CALCULATING CLASS WEIGHTS")
print("=" * 70)

from sklearn.utils.class_weight import compute_class_weight

# Calculate weights for each class
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

# Create a dictionary of weights
class_weight_dict = {i: weight for i, weight in enumerate(class_weights)}

print("Class weights calculated:")
for i, weight in class_weight_dict.items():
    class_name = le_target.classes_[i]
    print(f"   {class_name}: {weight:.2f}")

print("\n✅ Now use class_weight_dict in your models!")

#68
print("\n" + "=" * 70)
print("MODEL 1: LOGISTIC REGRESSION")
print("=" * 70)

lr_model = LogisticRegression(max_iter=2000, random_state=42, class_weight='balanced')
lr_model.fit(X_train_scaled, y_train)

y_pred_train_lr = lr_model.predict(X_train_scaled)
y_pred_test_lr = lr_model.predict(X_test_scaled)

train_acc_lr = accuracy_score(y_train, y_pred_train_lr)
test_acc_lr = accuracy_score(y_test, y_pred_test_lr)
f1_lr = f1_score(y_test, y_pred_test_lr, average='weighted')
precision_lr = precision_score(y_test, y_pred_test_lr, average='weighted', zero_division=0)
recall_lr = recall_score(y_test, y_pred_test_lr, average='weighted')

print(f"\n📊 Performance:")
print(f"   Train Accuracy: {train_acc_lr:.4f} ({train_acc_lr*100:.2f}%)")
print(f"   Test Accuracy:  {test_acc_lr:.4f} ({test_acc_lr*100:.2f}%)")
print(f"   F1-Score:       {f1_lr:.4f} ({f1_lr*100:.2f}%) ⭐")
print(f"   Precision:      {precision_lr:.4f} ({precision_lr*100:.2f}%)")
print(f"   Recall:         {recall_lr:.4f} ({recall_lr*100:.2f}%)")

# FIX: Limit classification report output
print(f"\n📋 Classification Report (Top 5 Classes):")
try:
    # Get the full report as a string
    report_str = classification_report(
        y_test,
        y_pred_test_lr,
        target_names=le_target.classes_,
        zero_division=0
    )

    # Split into lines and only show first 15 lines (header + top classes + summary)
    report_lines = report_str.split('\n')
    for line in report_lines[:15]:  # Limit output
        print(line)

    if len(report_lines) > 15:
        print(f"   ... ({len(le_target.classes_)} classes total)")
        # Show only the summary lines at the end
        for line in report_lines[-4:]:
            print(line)

except Exception as e:
    print(f"⚠️  Classification report skipped (too many classes): {e}")
    print(f"   Using aggregate metrics instead")

# FIX: Make confusion matrix optional and smaller
print(f"\n📊 Generating confusion matrix...")
try:
    cm_lr = confusion_matrix(y_test, y_pred_test_lr)

    # Only plot if we have reasonable number of classes (≤15)
    if len(le_target.classes_) <= 15:
        plt.figure(figsize=(12, 10))
        sns.heatmap(cm_lr, annot=True, fmt='d', cmap='Blues',
                    xticklabels=le_target.classes_,
                    yticklabels=le_target.classes_,
                    cbar_kws={'label': 'Count'})
        plt.title(f'Confusion Matrix - Logistic Regression (Acc: {test_acc_lr*100:.1f}%)',
                 fontsize=14, fontweight='bold')
        plt.ylabel('True Label')
        plt.xlabel('Predicted Label')
        plt.xticks(rotation=45, ha='right')
        plt.yticks(rotation=0)
        plt.tight_layout()
        plt.show()
    else:
        print(f"⚠️  Confusion matrix too large ({len(le_target.classes_)} classes) - skipping visualization")
        print(f"   Key metrics above are sufficient for evaluation")

except Exception as e:
    print(f"⚠️  Confusion matrix skipped: {e}")

# Store results
results['Logistic Regression'] = {
    'model': lr_model,
    'train_accuracy': train_acc_lr,
    'test_accuracy': test_acc_lr,
    'f1_weighted': f1_lr,
    'precision': precision_lr,
    'recall': recall_lr
}

print(f"\n✅ Logistic Regression training complete!")
print(f"=" * 70)

#69
print("\n" + "=" * 70)
print("MODEL 2: DECISION TREE")
print("=" * 70)

dt_model = DecisionTreeClassifier(
    random_state=42, max_depth=20, min_samples_split=10,
    min_samples_leaf=5, class_weight='balanced'
)
dt_model.fit(X_train_scaled, y_train)

y_pred_train_dt = dt_model.predict(X_train_scaled)
y_pred_test_dt = dt_model.predict(X_test_scaled)

train_acc_dt = accuracy_score(y_train, y_pred_train_dt) # Added train accuracy
test_acc_dt = accuracy_score(y_test, y_pred_test_dt)
f1_dt = f1_score(y_test, y_pred_test_dt, average='weighted')
precision_dt = precision_score(y_test, y_pred_test_dt, average='weighted', zero_division=0)
recall_dt = recall_score(y_test, y_pred_test_dt, average='weighted')

print(f"\n📊 Performance:")
print(f"   Train Accuracy: {train_acc_dt:.4f} ({train_acc_dt*100:.2f}%) # Added train accuracy")
print(f"   Test Accuracy:  {test_acc_dt:.4f} ({test_acc_dt*100:.2f}%) ")
print(f"   F1-Score:       {f1_dt:.4f} ({f1_dt*100:.2f}%) ⭐")
print(f"   Precision:      {precision_dt:.4f} ({precision_dt*100:.2f}%) ")
print(f"   Recall:         {recall_dt:.4f} ({recall_dt*100:.2f}%) ")

print(f"\n📋 Classification Report:")
print(classification_report(y_test, y_pred_test_dt, target_names=le_target.classes_, zero_division=0))

cm_dt = confusion_matrix(y_test, y_pred_test_dt)
plt.figure(figsize=(12, 10))
sns.heatmap(cm_dt, annot=True, fmt='d', cmap='Greens',
            xticklabels=le_target.classes_, yticklabels=le_target.classes_)
plt.title(f'Confusion Matrix - Decision Tree (Acc: {test_acc_dt*100:.1f}%)', fontsize=14, fontweight='bold')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

results['Decision Tree'] = {
    'model': dt_model,
    'train_accuracy': train_acc_dt, # Added train accuracy
    'test_accuracy': test_acc_dt,
    'f1_weighted': f1_dt,
    'precision': precision_dt,
    'recall': recall_dt
}

#70
print("\n" + "=" * 70)
print("MODEL 3: RANDOM FOREST (OPTIMIZED - ANTI-OVERFITTING)")
print("=" * 70)

# UPDATED: Regularized to prevent overfitting
rf_model = RandomForestClassifier(
    n_estimators=200,           # Reduced from 300
    random_state=42,
    max_depth=15,               # Reduced from 25 to prevent overfitting
    min_samples_split=15,       # Increased from 5
    min_samples_leaf=5,         # Increased from 2
    max_features='sqrt',
    class_weight='balanced',
    n_jobs=-1,
    bootstrap=True,
    max_samples=0.8             # Use 80% of data for each tree
)

rf_model.fit(X_train_scaled, y_train)

# Predictions
y_pred_train_rf = rf_model.predict(X_train_scaled)
y_pred_test_rf = rf_model.predict(X_test_scaled)

# Calculate metrics
train_acc_rf = accuracy_score(y_train, y_pred_train_rf)
test_acc_rf = accuracy_score(y_test, y_pred_test_rf)
f1_rf = f1_score(y_test, y_pred_test_rf, average='weighted')
precision_rf = precision_score(y_test, y_pred_test_rf, average='weighted', zero_division=0)
recall_rf = recall_score(y_test, y_pred_test_rf, average='weighted')

# Display metrics
print(f"\n📊 Performance:")
print(f"   Train Accuracy: {train_acc_rf:.4f} ({train_acc_rf*100:.2f}%)")
print(f"   Test Accuracy:  {test_acc_rf:.4f} ({test_acc_rf*100:.2f}%)")
print(f"   F1-Score:       {f1_rf:.4f} ({f1_rf*100:.2f}%) ⭐")
print(f"   Precision:      {precision_rf:.4f} ({precision_rf*100:.2f}%)")
print(f"   Recall:         {recall_rf:.4f} ({recall_rf*100:.2f}%)")

# Overfitting check
overfit_gap = train_acc_rf - test_acc_rf
print(f"\n🔍 Overfitting Check:")
print(f"   Gap (Train - Test): {overfit_gap*100:.2f}%")
if overfit_gap > 0.15:
    print(f"   ⚠️  WARNING: Overfitting! Gap > 15%")
elif overfit_gap > 0.10:
    print(f"   ⚠️  Slight overfitting")
else:
    print(f"   ✅ No overfitting - Model generalizes well!")

# Classification Report
print(f"\n📋 Classification Report:")
print(classification_report(y_test, y_pred_test_rf, target_names=le_target.classes_, zero_division=0))

# Confusion Matrix
cm_rf = confusion_matrix(y_test, y_pred_test_rf)
plt.figure(figsize=(12, 10))
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Oranges',
            xticklabels=le_target.classes_,
            yticklabels=le_target.classes_)
plt.title(f'Confusion Matrix - Random Forest (Acc: {test_acc_rf*100:.1f}%)', fontsize=14, fontweight='bold')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Feature Importance
print(f"\n🎯 Feature Importance (Top 15):")
feature_importance_rf = pd.DataFrame({
    'Feature': feature_columns,
    'Importance': rf_model.feature_importances_
}).sort_values('Importance', ascending=False)
print(feature_importance_rf.head(15).to_string(index=False))

# Store results
results['Random Forest'] = {
    'model': rf_model,
    'train_accuracy': train_acc_rf,
    'test_accuracy': test_acc_rf,
    'f1_weighted': f1_rf,
    'precision': precision_rf,
    'recall': recall_rf
}

print("\n✓ Random Forest training complete")

#71
print("\n" + "=" * 70)
print("MODEL 4: GRADIENT BOOSTING (OPTIMIZED - ANTI-OVERFITTING)")
print("=" * 70)

# UPDATED: With early stopping and regularization
gb_model = GradientBoostingClassifier(
    n_estimators=150,           # Reduced from 200
    random_state=42,
    max_depth=6,                # Reduced from 10
    learning_rate=0.05,         # Reduced from 0.1
    min_samples_split=20,
    min_samples_leaf=10,
    subsample=0.8,
    max_features='sqrt',
    validation_fraction=0.1,    # For early stopping
    n_iter_no_change=10,        # Stop if no improvement
    tol=0.001
)

gb_model.fit(X_train_scaled, y_train)

# Predictions
y_pred_train_gb = gb_model.predict(X_train_scaled)
y_pred_test_gb = gb_model.predict(X_test_scaled)

# Calculate metrics
train_acc_gb = accuracy_score(y_train, y_pred_train_gb)
test_acc_gb = accuracy_score(y_test, y_pred_test_gb)
f1_gb = f1_score(y_test, y_pred_test_gb, average='weighted')
precision_gb = precision_score(y_test, y_pred_test_gb, average='weighted', zero_division=0)
recall_gb = recall_score(y_test, y_pred_test_gb, average='weighted')

# Display metrics
print(f"\n📊 Performance:")
print(f"   Train Accuracy: {train_acc_gb:.4f} ({train_acc_gb*100:.2f}%)")
print(f"   Test Accuracy:  {test_acc_gb:.4f} ({test_acc_gb*100:.2f}%)")
print(f"   F1-Score:       {f1_gb:.4f} ({f1_gb*100:.2f}%) ⭐")
print(f"   Precision:      {precision_gb:.4f} ({precision_gb*100:.2f}%)")
print(f"   Recall:         {recall_gb:.4f} ({recall_gb*100:.2f}%)")

# Overfitting check
overfit_gap = train_acc_gb - test_acc_gb
print(f"\n🔍 Overfitting Check:")
print(f"   Gap (Train - Test): {overfit_gap*100:.2f}%")
if overfit_gap > 0.15:
    print(f"   ⚠️  WARNING: Overfitting! Gap > 15%")
elif overfit_gap > 0.10:
    print(f"   ⚠️  Slight overfitting")
else:
    print(f"   ✅ No overfitting!")

# Classification Report
print(f"\n📋 Classification Report:")
print(classification_report(y_test, y_pred_test_gb, target_names=le_target.classes_, zero_division=0))

# Confusion Matrix
cm_gb = confusion_matrix(y_test, y_pred_test_gb)
plt.figure(figsize=(12, 10))
sns.heatmap(cm_gb, annot=True, fmt='d', cmap='Purples',
            xticklabels=le_target.classes_,
            yticklabels=le_target.classes_)
plt.title(f'Confusion Matrix - Gradient Boosting (Acc: {test_acc_gb*100:.1f}%)', fontsize=14, fontweight='bold')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# Store results
results['Gradient Boosting'] = {
    'model': gb_model,
    'train_accuracy': train_acc_gb,
    'test_accuracy': test_acc_gb,
    'f1_weighted': f1_gb,
    'precision': precision_gb,
    'recall': recall_gb
}

print("\n✓ Gradient Boosting training complete")

#73
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

print("\n" + "=" * 70)
print("MODEL 5: XGBOOST (OPTIMIZED - ANTI-OVERFITTING)")
print("=" * 70)

# UPDATED: With L1/L2 regularization
xgb_risk_model = XGBClassifier(
    n_estimators=150,
    max_depth=6,                # Reduced
    learning_rate=0.05,         # Slower learning
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=5,         # Increased for regularization
    gamma=0.1,                  # Minimum loss reduction
    reg_alpha=0.1,              # L1 regularization
    reg_lambda=1.0,             # L2 regularization
    random_state=42,
    eval_metric='mlogloss',
    verbosity=0
)

xgb_risk_model.fit(X_train_scaled, y_train)

# Predictions
y_pred_train_xgb_risk = xgb_risk_model.predict(X_train_scaled)
y_pred_test_xgb_risk = xgb_risk_model.predict(X_test_scaled)

# Calculate metrics
train_acc_xgb_risk = accuracy_score(y_train, y_pred_train_xgb_risk)
test_acc_xgb_risk = accuracy_score(y_test, y_pred_test_xgb_risk)
f1_xgb_risk = f1_score(y_test, y_pred_test_xgb_risk, average='weighted')
precision_xgb_risk = precision_score(y_test, y_pred_test_xgb_risk, average='weighted', zero_division=0)
recall_xgb_risk = recall_score(y_test, y_pred_test_xgb_risk, average='weighted')

# Display metrics
print(f"\n📊 Performance:")
print(f"   Train Accuracy: {train_acc_xgb_risk:.4f} ({train_acc_xgb_risk*100:.2f}%)")
print(f"   Test Accuracy:  {test_acc_xgb_risk:.4f} ({test_acc_xgb_risk*100:.2f}%)")
print(f"   F1-Score:       {f1_xgb_risk:.4f} ({f1_xgb_risk*100:.2f}%) ⭐")
print(f"   Precision:      {precision_xgb_risk:.4f} ({precision_xgb_risk*100:.2f}%)")
print(f"   Recall:         {recall_xgb_risk:.4f} ({recall_xgb_risk*100:.2f}%)")

# Overfitting check
overfit_gap = train_acc_xgb_risk - test_acc_xgb_risk
print(f"\n🔍 Overfitting Check:")
print(f"   Gap (Train - Test): {overfit_gap*100:.2f}%")
if overfit_gap > 0.15:
    print(f"   ⚠️  WARNING: Overfitting!")
elif overfit_gap > 0.10:
    print(f"   ⚠️  Slight overfitting")
else:
    print(f"   ✅ No overfitting!")

# Classification Report
print(f"\n📋 Classification Report:")
print(classification_report(y_test, y_pred_test_xgb_risk, target_names=le_target.classes_, zero_division=0))

# Confusion Matrix - FIXED: No more overlapping labels!
print(f"\n🔲 Confusion Matrix:")
cm_xgb_risk = confusion_matrix(y_test, y_pred_test_xgb_risk)

# FIXED: Larger size and better spacing
fig, ax = plt.subplots(figsize=(14, 12))
sns.heatmap(cm_xgb_risk, annot=True, fmt='d', cmap='Blues',
            xticklabels=le_target.classes_,
            yticklabels=le_target.classes_,
            ax=ax,
            cbar_kws={'shrink': 0.8})

plt.title(f'Confusion Matrix - XGBoost (Acc: {test_acc_xgb_risk*100:.1f}%)', fontsize=16, fontweight='bold', pad=20)
plt.ylabel('True Label', fontsize=13)
plt.xlabel('Predicted Label', fontsize=13)

# FIXED: Better rotation and font size
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(rotation=0, fontsize=10)

plt.tight_layout()
plt.show()

# Store results
results['XGBoost'] = {
    'model': xgb_risk_model,
    'train_accuracy': train_acc_xgb_risk,
    'test_accuracy': test_acc_xgb_risk,
    'f1_weighted': f1_xgb_risk,
    'precision': precision_xgb_risk,
    'recall': recall_xgb_risk
}

print("\n✓ XGBoost training complete")

#74
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore', category=UserWarning)

print("\n" + "=" * 70)
print("MODEL 6: LIGHTGBM (OPTIMIZED - ANTI-OVERFITTING)")
print("=" * 70)

# UPDATED: With regularization
lgbm_risk_model = LGBMClassifier(
    n_estimators=150,
    max_depth=6,                # Reduced
    learning_rate=0.05,         # Slower
    num_leaves=31,              # Reduced
    min_child_samples=20,       # Increased
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,              # L1 regularization
    reg_lambda=1.0,             # L2 regularization
    random_state=42,
    verbose=-1
)

lgbm_risk_model.fit(X_train_scaled, y_train)

# Predictions
y_pred_train_lgbm_risk = lgbm_risk_model.predict(X_train_scaled)
y_pred_test_lgbm_risk = lgbm_risk_model.predict(X_test_scaled)

# Calculate metrics
train_acc_lgbm_risk = accuracy_score(y_train, y_pred_train_lgbm_risk)
test_acc_lgbm_risk = accuracy_score(y_test, y_pred_test_lgbm_risk)
f1_lgbm_risk = f1_score(y_test, y_pred_test_lgbm_risk, average='weighted')
precision_lgbm_risk = precision_score(y_test, y_pred_test_lgbm_risk, average='weighted', zero_division=0)
recall_lgbm_risk = recall_score(y_test, y_pred_test_lgbm_risk, average='weighted')

# Display metrics
print(f"\n📊 Performance:")
print(f"   Train Accuracy: {train_acc_lgbm_risk:.4f} ({train_acc_lgbm_risk*100:.2f}%)")
print(f"   Test Accuracy:  {test_acc_lgbm_risk:.4f} ({test_acc_lgbm_risk*100:.2f}%)")
print(f"   F1-Score:       {f1_lgbm_risk:.4f} ({f1_lgbm_risk*100:.2f}%) ⭐")
print(f"   Precision:      {precision_lgbm_risk:.4f} ({precision_lgbm_risk*100:.2f}%)")
print(f"   Recall:         {recall_lgbm_risk:.4f} ({recall_lgbm_risk*100:.2f}%)")

# Overfitting check
overfit_gap = train_acc_lgbm_risk - test_acc_lgbm_risk
print(f"\n🔍 Overfitting Check:")
print(f"   Gap (Train - Test): {overfit_gap*100:.2f}%")
if overfit_gap > 0.15:
    print(f"   ⚠️  WARNING: Overfitting!")
elif overfit_gap > 0.10:
    print(f"   ⚠️  Slight overfitting")
else:
    print(f"   ✅ No overfitting!")

# Classification Report
print(f"\n📋 Classification Report:")
print(classification_report(y_test, y_pred_test_lgbm_risk, target_names=le_target.classes_, zero_division=0))

# Confusion Matrix - FIXED: No more overlapping!
print(f"\n🔲 Confusion Matrix:")
cm_lgbm_risk = confusion_matrix(y_test, y_pred_test_lgbm_risk)

# FIXED: Larger size and better spacing
fig, ax = plt.subplots(figsize=(14, 12))
sns.heatmap(cm_lgbm_risk, annot=True, fmt='d', cmap='Greens',
            xticklabels=le_target.classes_,
            yticklabels=le_target.classes_,
            ax=ax,
            cbar_kws={'shrink': 0.8})

plt.title(f'Confusion Matrix - LightGBM (Acc: {test_acc_lgbm_risk*100:.1f}%)', fontsize=16, fontweight='bold', pad=20)
plt.ylabel('True Label', fontsize=13)
plt.xlabel('Predicted Label', fontsize=13)

# FIXED: Better rotation and font size
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(rotation=0, fontsize=10)

plt.tight_layout()
plt.show()

# Store results
results['LightGBM'] = {
    'model': lgbm_risk_model,
    'train_accuracy': train_acc_lgbm_risk,
    'test_accuracy': test_acc_lgbm_risk,
    'f1_weighted': f1_lgbm_risk,
    'precision': precision_lgbm_risk,
    'recall': recall_lgbm_risk
}

print("\n✓ LightGBM training complete")

#75
from catboost import CatBoostClassifier

print("\n" + "=" * 70)
print("MODEL 7: CATBOOST (NEW - OFTEN BEST PERFORMER!)")
print("=" * 70)

# CatBoost with regularization
catboost_model = CatBoostClassifier(
    iterations=200,
    depth=6,
    learning_rate=0.05,
    l2_leaf_reg=3,              # L2 regularization
    random_seed=42,
    verbose=False,
    loss_function='MultiClass',
    eval_metric='TotalF1:average=Weighted'
)

catboost_model.fit(X_train_scaled, y_train)

# Predictions
y_pred_train_cat = catboost_model.predict(X_train_scaled)
y_pred_test_cat = catboost_model.predict(X_test_scaled)

# Calculate metrics
train_acc_cat = accuracy_score(y_train, y_pred_train_cat)
test_acc_cat = accuracy_score(y_test, y_pred_test_cat)
f1_cat = f1_score(y_test, y_pred_test_cat, average='weighted')
precision_cat = precision_score(y_test, y_pred_test_cat, average='weighted', zero_division=0)
recall_cat = recall_score(y_test, y_pred_test_cat, average='weighted')

# Display metrics
print(f"\n Performance:")
print(f"   Train Accuracy: {train_acc_cat:.4f} ({train_acc_cat*100:.2f}%)")
print(f"   Test Accuracy:  {test_acc_cat:.4f} ({test_acc_cat*100:.2f}%)")
print(f"   F1-Score:       {f1_cat:.4f} ({f1_cat*100:.2f}%) ⭐")
print(f"   Precision:      {precision_cat:.4f} ({precision_cat*100:.2f}%)")
print(f"   Recall:         {recall_cat:.4f} ({recall_cat*100:.2f}%)")

# Overfitting check
overfit_cat = train_acc_cat - test_acc_cat
print(f"\n Overfitting Check:")
print(f"   Gap (Train - Test): {overfit_cat*100:.2f}%")
if overfit_cat < 0.10:
    print(f"    Excellent! No overfitting!")
elif overfit_cat < 0.15:
    print(f"    Good - Minimal overfitting")
else:
    print(f"     Some overfitting detected")

# Classification Report
print(f"\n Classification Report:")
print(classification_report(y_test, y_pred_test_cat, target_names=le_target.classes_, zero_division=0))

# Confusion Matrix
cm_cat = confusion_matrix(y_test, y_pred_test_cat)
fig, ax = plt.subplots(figsize=(14, 12))
sns.heatmap(cm_cat, annot=True, fmt='d', cmap='RdPu',
            xticklabels=le_target.classes_,
            yticklabels=le_target.classes_,
            ax=ax,
            cbar_kws={'shrink': 0.8})

plt.title(f'Confusion Matrix - CatBoost (Acc: {test_acc_cat*100:.1f}%)', fontsize=16, fontweight='bold', pad=20)
plt.ylabel('True Label', fontsize=13)
plt.xlabel('Predicted Label', fontsize=13)
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(rotation=0, fontsize=10)
plt.tight_layout()
plt.show()

# Store results - IMPORTANT: This adds CatBoost to comparison
results['CatBoost'] = {
    'model': catboost_model,
    'train_accuracy': train_acc_cat,
    'test_accuracy': test_acc_cat,
    'f1_weighted': f1_cat,
    'precision': precision_cat,
    'recall': recall_cat
}

print("\n✓ CatBoost training complete")

#75.6 - VOTING ENSEMBLE WITH CONFUSION MATRIX & RESULTS TABLE
from sklearn.ensemble import VotingClassifier
import pandas as pd

print("\n" + "=" * 70)
print("🎯 SIMPLE VOTING ENSEMBLE - COMBINING BEST 3 MODELS")
print("=" * 70)

# Use your 3 best models (XGBoost, CatBoost, Random Forest)
simple_ensemble = VotingClassifier(
    estimators=[
        ('xgb', xgb_risk_model),
        ('cat', catboost_model),
        ('rf', rf_model)
    ],
    voting='soft',  # Use probabilities
    weights=[2, 2, 1]  # XGBoost and CatBoost get more weight
)

print("Training simple ensemble...")
simple_ensemble.fit(X_train_scaled, y_train)

# Predictions
y_pred_train_ensemble = simple_ensemble.predict(X_train_scaled)
y_pred_ensemble = simple_ensemble.predict(X_test_scaled)

# Metrics
train_acc_ensemble = accuracy_score(y_train, y_pred_train_ensemble)
ensemble_acc = accuracy_score(y_test, y_pred_ensemble)
ensemble_f1 = f1_score(y_test, y_pred_ensemble, average='weighted')
ensemble_precision = precision_score(y_test, y_pred_ensemble, average='weighted', zero_division=0)
ensemble_recall = recall_score(y_test, y_pred_ensemble, average='weighted')

# ============================================================================
# RESULTS TABLE
# ============================================================================
print(f"\n📊 ENSEMBLE PERFORMANCE:")
print("=" * 70)

# Create a nice formatted table
results_table = pd.DataFrame({
    'Metric': ['Train Accuracy', 'Test Accuracy', 'F1-Score', 'Precision', 'Recall'],
    'Score': [
        f'{train_acc_ensemble:.4f}',
        f'{ensemble_acc:.4f}',
        f'{ensemble_f1:.4f}',
        f'{ensemble_precision:.4f}',
        f'{ensemble_recall:.4f}'
    ],
    'Percentage': [
        f'{train_acc_ensemble*100:.2f}%',
        f'{ensemble_acc*100:.2f}%',
        f'{ensemble_f1*100:.2f}%',
        f'{ensemble_precision*100:.2f}%',
        f'{ensemble_recall*100:.2f}%'
    ]
})

print("\n" + results_table.to_string(index=False))

# Overfitting check
overfit_gap = train_acc_ensemble - ensemble_acc
print(f"\n🔍 Overfitting Check:")
print(f"   Gap (Train - Test): {overfit_gap*100:.2f}%")
if overfit_gap < 0.05:
    print("   ✅ Excellent! No overfitting")
elif overfit_gap < 0.10:
    print("   ✅ Good! Minimal overfitting")
else:
    print("   ⚠️  Some overfitting detected")

# ============================================================================
# CONFUSION MATRIX
# ============================================================================
print(f"\n📊 Confusion Matrix:")
print("=" * 70)

cm_ensemble = confusion_matrix(y_test, y_pred_ensemble)

# Only plot if reasonable number of classes
if len(le_target.classes_) <= 15:
    plt.figure(figsize=(12, 10))
    sns.heatmap(cm_ensemble, annot=True, fmt='d', cmap='Blues',
                xticklabels=le_target.classes_,
                yticklabels=le_target.classes_,
                cbar_kws={'label': 'Count'})
    plt.title(f'Confusion Matrix - Voting Ensemble\nAccuracy: {ensemble_acc*100:.1f}% | F1-Score: {ensemble_f1*100:.1f}%',
             fontsize=14, fontweight='bold', pad=20)
    plt.ylabel('True Label', fontsize=12)
    plt.xlabel('Predicted Label', fontsize=12)
    plt.xticks(rotation=45, ha='right')
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.show()

    print("✅ Confusion matrix displayed above")
else:
    print(f"⚠️  Too many classes ({len(le_target.classes_)}) for clear visualization")
    print("   Showing confusion matrix summary instead:")
    print(f"\n   Diagonal (correct predictions): {np.trace(cm_ensemble)}/{np.sum(cm_ensemble)}")

# ============================================================================
# PER-CLASS PERFORMANCE TABLE
# ============================================================================
print(f"\n📋 Per-Class Performance:")
print("=" * 70)

# Calculate per-class metrics
from sklearn.metrics import precision_recall_fscore_support

precision_per_class, recall_per_class, f1_per_class, support_per_class = \
    precision_recall_fscore_support(y_test, y_pred_ensemble, zero_division=0)

# Create per-class table
per_class_df = pd.DataFrame({
    'Disease': le_target.classes_,
    'Precision': [f'{p*100:.1f}%' for p in precision_per_class],
    'Recall': [f'{r*100:.1f}%' for r in recall_per_class],
    'F1-Score': [f'{f*100:.1f}%' for f in f1_per_class],
    'Samples': support_per_class
})

# Sort by F1-Score (best performing first)
per_class_df['F1_numeric'] = f1_per_class
per_class_df = per_class_df.sort_values('F1_numeric', ascending=False)
per_class_df = per_class_df.drop('F1_numeric', axis=1)

print("\n" + per_class_df.to_string(index=False))

# ============================================================================
# SAVE TO RESULTS
# ============================================================================
results['Simple Ensemble'] = {
    'model': simple_ensemble,
    'train_accuracy': train_acc_ensemble,
    'test_accuracy': ensemble_acc,
    'f1_weighted': ensemble_f1,
    'precision': ensemble_precision,
    'recall': ensemble_recall
}

print("\n" + "=" * 70)
print("✅ ENSEMBLE COMPLETE - This is usually your BEST model!")
print("=" * 70)

#76
print("\n" + "=" * 70)
print("RISK PREDICTION - ALL MODELS COMPARISON")
print("=" * 70)

# Create comparison DataFrame with ALL models (now includes CatBoost!)
comparison_df = pd.DataFrame({
    'Model': list(results.keys()),
    'Train Accuracy': [f"{results[m]['train_accuracy']*100:.2f}%" for m in results.keys()],
    'Test Accuracy': [f"{results[m]['test_accuracy']*100:.2f}%" for m in results.keys()],
    'F1-Score': [f"{results[m]['f1_weighted']*100:.2f}%" for m in results.keys()],
    'Precision': [f"{results[m]['precision']*100:.2f}%" for m in results.keys()],
    'Recall': [f"{results[m]['recall']*100:.2f}%" for m in results.keys()]
})

print("\n" + comparison_df.to_string(index=False))

# Find best model based on F1-Score
best_model_name = max(results, key=lambda x: results[x]['f1_weighted'])
best_model_obj = results[best_model_name]['model']

print("\n" + "=" * 70)
print(f" BEST MODEL: {best_model_name}")
print("=" * 70)
print(f"\nSelected based on F1-Score (Weighted) - Best for medical platforms!")
print(f"\n Performance:")
print(f"   • Train Accuracy: {results[best_model_name]['train_accuracy']*100:.2f}%")
print(f"   • Test Accuracy:  {results[best_model_name]['test_accuracy']*100:.2f}%")
print(f"   • F1-Score:       {results[best_model_name]['f1_weighted']*100:.2f}% ⭐")
print(f"   • Precision:      {results[best_model_name]['precision']*100:.2f}%")
print(f"   • Recall:         {results[best_model_name]['recall']*100:.2f}%")

# Overfitting analysis
train_acc = results[best_model_name]['train_accuracy']
test_acc = results[best_model_name]['test_accuracy']
overfit_gap = train_acc - test_acc

print(f"\n Overfitting Analysis:")
print(f"   • Train Accuracy: {train_acc*100:.2f}%")
print(f"   • Test Accuracy:  {test_acc*100:.2f}%")
print(f"   • Gap:            {overfit_gap*100:.2f}%")

if overfit_gap > 0.15:
    print(f"     WARNING: Significant overfitting! (Gap > 15%)")
elif overfit_gap > 0.10:
    print(f"     Slight overfitting (Gap = {overfit_gap*100:.1f}%)者に確認してください。")
else:
    print(f"    No overfitting - Model generalizes well!")

# Visualize ALL models comparison
plt.figure(figsize=(15, 6))

models_list = list(results.keys())
test_accs = [results[m]['test_accuracy'] * 100 for m in models_list]
f1_scores = [results[m]['f1_weighted'] * 100 for m in models_list]

x = np.arange(len(models_list))
width = 0.35

plt.bar(x - width/2, test_accs, width, label='Test Accuracy', alpha=0.8, color='steelblue')
plt.bar(x + width/2, f1_scores, width, label='F1-Score', alpha=0.8, color='darkorange')

plt.xlabel('Models', fontsize=12, fontweight='bold')
plt.ylabel('Score (%)', fontsize=12, fontweight='bold')
plt.title('All Risk Prediction Models - Performance Comparison', fontsize=14, fontweight='bold')
plt.xticks(x, models_list, rotation=30, ha='right')
plt.legend(fontsize=11)
plt.ylim(0, 100)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

print(f"\n Comparison complete! All {len(results)} models compared.")

#77
preventive_measures = {
    'Diabetes_Related': {
        'short_term': [
            'Monitor blood glucose levels daily',
            'Avoid sugary foods and refined carbohydrates',
            'Stay hydrated with water',
            'Take prescribed medications on time'
        ],
        'long_term': [
            'Follow a low-glycemic diet',
            'Exercise for 30 minutes, 5 days/week',
            'Maintain healthy body weight (BMI < 25)',
            'Regular HbA1c testing every 3 months'
        ],
        'lifestyle': [
            'Quit smoking',
            'Limit alcohol',
            'Manage stress',
            'Get 7-8 hours sleep'
        ]
    },
    'Kidney_Disease': {
        'short_term': [
            'Monitor creatinine levels monthly',
            'Stay hydrated (8-10 glasses water daily)',
            'Reduce salt intake (<5g/day)',
            'Avoid NSAIDs without approval'
        ],
        'long_term': [
            'Control blood pressure (<130/80)',
            'Manage diabetes if present',
            'Follow low-protein diet if recommended',
            'Regular kidney function tests'
        ],
        'lifestyle': [
            'Quit smoking',
            'Maintain healthy weight',
            'Regular exercise (walking, swimming)',
            'Limit processed foods'
        ]
    },
    'Cardiovascular_Disease': {
        'short_term': [
            'Monitor blood pressure twice daily',
            'Take heart medications as prescribed',
            'Limit sodium (<2g/day)',
            'Recognize warning signs (chest pain, SOB)'
        ],
        'long_term': [
            'Follow Mediterranean diet',
            'Exercise 30-45 min, 5 days/week',
            'Maintain healthy cholesterol',
            'Regular ECG and stress tests'
        ],
        'lifestyle': [
            'Stop smoking',
            'Limit alcohol',
            'Manage stress',
            'Maintain healthy weight'
        ]
    },
    'Infection': {
        'short_term': [
            'Complete antibiotic course',
            'Practice hand hygiene',
            'Get adequate rest',
            'Stay hydrated'
        ],
        'long_term': [
            'Strengthen immune system',
            'Keep vaccinations updated',
            'Regular health check-ups',
            'Treat chronic conditions'
        ],
        'lifestyle': [
            'Avoid sick contacts',
            'Good personal hygiene',
            'Eat immune-boosting foods',
            'Regular exercise'
        ]
    },
    'Respiratory_Disease': {
        'short_term': [
            'Use prescribed inhalers correctly',
            'Avoid air pollution and irritants',
            'Practice breathing exercises',
            'Monitor oxygen saturation'
        ],
        'long_term': [
            'Regular lung function tests',
            'Pulmonary rehabilitation',
            'Maintain healthy weight',
            'Annual flu and pneumonia vaccinations'
        ],
        'lifestyle': [
            'Quit smoking immediately',
            'Avoid secondhand smoke',
            'Use air purifiers at home',
            'Regular aerobic exercise'
        ]
    },
    'Liver_Disease': {
        'short_term': [
            'Avoid alcohol completely',
            'Monitor liver enzymes regularly',
            'Take prescribed medications',
            'Watch for worsening signs'
        ],
        'long_term': [
            'Hepatitis vaccinations (A and B)',
            'Low-fat, high-fiber diet',
            'Regular liver function tests',
            'Maintain healthy weight'
        ],
        'lifestyle': [
            'Absolutely no alcohol',
            'Avoid hepatotoxic medications',
            'Regular exercise',
            'Adequate protein intake'
        ]
    },
    'Other_Condition': {
        'short_term': [
            'Follow doctor\'s treatment plan',
            'Monitor symptoms daily',
            'Take medications as prescribed',
            'Attend follow-up appointments'
        ],
        'long_term': [
            'Regular health check-ups',
            'Maintain balanced diet',
            'Regular physical activity',
            'Preventive screenings'
        ],
        'lifestyle': [
            'Healthy lifestyle habits',
            'Stress management',
            'Adequate sleep',
            'Social support'
        ]
    }
}

risk_based_measures = {
    'High_Diabetes_Risk': [
        ' HIGH DIABETES RISK',
        'Schedule HbA1c test within 1 week',
        'Cut refined sugars immediately',
        'Start daily 30-minute walks'
    ],
    'High_Kidney_Risk': [
        ' KIDNEY DYSFUNCTION RISK',
        'Check creatinine and GFR within 3 days',
        'Reduce protein intake',
        'Monitor BP twice daily'
    ],
    'High_BP_Risk': [
        ' HYPERTENSION RISK',
        'Monitor BP twice daily',
        'Reduce sodium to <2g/day',
        'Start DASH diet'
    ],
    'Anemia_Risk': [
        ' ANEMIA DETECTED',
        'Increase iron-rich foods',
        'Vitamin C with meals',
        'Check iron, B12, folate levels'
    ]
}

print(" Preventive measures database created")

#78
def predict_patient_risk(patient_data, model, scaler, le_target,
                        feature_columns, preventive_measures, risk_based_measures):
    """Predict disease risk and provide preventive measures"""

    # Prepare features
    X_patient = patient_data[feature_columns].copy()
    X_patient_scaled = scaler.transform(X_patient)

    # Predict
    prediction = model.predict(X_patient_scaled)[0]
    prediction_proba = model.predict_proba(X_patient_scaled)[0]

    # Get disease category
    predicted_disease = le_target.inverse_transform([prediction])[0]
    confidence = prediction_proba[prediction] * 100

    # Get top 3 risks
    top_3_indices = np.argsort(prediction_proba)[-3:][::-1]
    top_3_diseases = le_target.inverse_transform(top_3_indices)
    top_3_probas = prediction_proba[top_3_indices] * 100

    # Identify active risk factors
    active_risks = []
    if patient_data['Diabetes_Risk'].values[0] == 1:
        active_risks.extend(risk_based_measures.get('High_Diabetes_Risk', []))
    if patient_data['Kidney_Dysfunction_Risk'].values[0] == 1:
        active_risks.extend(risk_based_measures.get('High_Kidney_Risk', []))
    if patient_data['Hypertension_Risk'].values[0] == 1:
        active_risks.extend(risk_based_measures.get('High_BP_Risk', []))
    if patient_data['Anemia_Risk'].values[0] == 1:
        active_risks.extend(risk_based_measures.get('Anemia_Risk', []))

    # Get preventive measures
    disease_measures = preventive_measures.get(predicted_disease, preventive_measures.get('Other_Condition', {}))

    # Risk level
    risk_level = 'HIGH' if confidence > 70 else 'MODERATE' if confidence > 50 else 'LOW'
    timeline = '1-3 months' if confidence > 70 else '3-6 months' if confidence > 50 else '6-12 months'

    return {
        'disease': predicted_disease,
        'confidence': confidence,
        'risk_level': risk_level,
        'timeline': timeline,
        'top_risks': list(zip(top_3_diseases, top_3_probas)),
        'active_risks': active_risks,
        'preventive_measures': disease_measures
    }

print("✓ Prediction function created")

#79
print("\n" + "=" * 70)
print("SAMPLE PATIENT PREDICTIONS")
print("=" * 70)

# Test on 3 random patients
for i in range(3):
    sample = X_test.iloc[[i]]

    result = predict_patient_risk(
        sample, best_model_obj, scaler, le_target,
        feature_columns, preventive_measures, risk_based_measures
    )

    print(f"\n{'='*70}")
    print(f"PATIENT #{i+1}")
    print(f"{'='*70}")
    print(f"\n Prediction: {result['disease']}")
    print(f"   Confidence: {result['confidence']:.1f}%")
    print(f"   Risk Level: {result['risk_level']}")
    print(f"   Timeline: {result['timeline']}")

    print(f"\n   Top 3 Risk Predictions:")
    for disease, prob in result['top_risks']:
        print(f"      {prob:5.1f}% - {disease}")

    if result['active_risks']:
        print(f"\n  Active Risk Factors:")
        for risk in result['active_risks'][:4]:
            print(f"   • {risk}")

    if result['preventive_measures']:
        print(f"\n Recommended Preventive Measures:")
        print(f"\n   Short-term (Next 3 months):")
        for action in result['preventive_measures'].get('short_term', [])[:3]:
            print(f"   ✓ {action}")

        print(f"\n   Long-term (6-12 months):")
        for action in result['preventive_measures'].get('long_term', [])[:3]:
            print(f"   ✓ {action}")


# ====================================================================================
# : Save Model for Production
# ====================================================================================
import pickle

# Save all components
with open('patient_risk_model.pkl', 'wb') as f:
    pickle.dump(best_model_obj, f)

with open('feature_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(le_target, f)

with open('feature_columns.pkl', 'wb') as f:
    pickle.dump(feature_columns, f)

with open('preventive_measures.pkl', 'wb') as f:
    pickle.dump(preventive_measures, f)

with open('risk_based_measures.pkl', 'wb') as f:
    pickle.dump(risk_based_measures, f)

print("✓ Model saved successfully!")
print("\nFiles created:")
print("  • patient_risk_model.pkl")
print("  • feature_scaler.pkl")
print("  • label_encoder.pkl")
print("  • feature_columns.pkl")
print("  • preventive_measures.pkl")
print("  • risk_based_measures.pkl")


# ====================================================================================
#  Final Summary
# ====================================================================================
print("\n" + "=" * 70)
print("FINAL MODEL EVALUATION SUMMARY")
print("=" * 70)

print(f"\n Best Model: {best_model_name}")
print(f"\n Performance Metrics:")
print(f"   • Test Accuracy:  {results[best_model_name]['test_accuracy']:.2%}")
print(f"   • F1-Score:       {results[best_model_name]['f1_weighted']:.2%} ⭐")
print(f"   • Precision:      {results[best_model_name]['precision']:.2%}")
print(f"   • Recall:         {results[best_model_name]['recall']:.2%}")

print("\n METRIC TO USE: F1-Score (Weighted)")
print("   This is the BEST metric for medical platforms!")
print("   It balances precision and recall")

f1 = results[best_model_name]['f1_weighted']
if f1 >= 0.85:
    print(f"\n EXCELLENT ({f1:.1%}) - Ready for production!")
elif f1 >= 0.75:
    print(f"\n GOOD ({f1:.1%}) - Suitable with monitoring")
elif f1 >= 0.65:
    print(f"\n  MODERATE ({f1:.1%}) - Needs improvement")
else:
    print(f"\n NEEDS WORK ({f1:.1%}) - Collect more data")

print("\n" + "=" * 70)
print(" PATIENT RISK PREDICTION MODEL COMPLETE!")
print("=" * 70)