# -*- coding: utf-8 -*-
"""smart_connect_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bs1UW9_37nXcJs3F1MT9J-xfZ-i9Ehwq
"""

import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import pip
import seaborn as sns

# Preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

# Imbalance
from imblearn.over_sampling import SMOTE

# Models
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# Evaluation
from sklearn.metrics import classification_report, confusion_matrix

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, classification_report, confusion_matrix,
                             roc_auc_score, roc_curve)
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("raian1400.csv")

print(df.shape)
df.head()

print("\n📌 Columns:")
print(df.columns.tolist())

print("\n📌 Data Types:")
print(df.dtypes)

print("\n📌 Missing Values:")
print(df.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12,4))
sns.countplot(y=df['Diagnosis'], order=df['Diagnosis'].value_counts().index)
plt.title("Raw Diagnosis Distribution (Before Cleaning)")
plt.show()

plt.figure(figsize=(14,6))
sns.heatmap(df.isnull(), cbar=False)
plt.title("Missing Values Heatmap (Before Cleaning)")
plt.show()

plt.figure(figsize=(12,4))
sns.boxplot(x='Diagnosis', y='Age', data=df)
plt.xticks(rotation=90)
plt.title("Age Distribution per Diagnosis (Raw)")
plt.show()

plt.figure(figsize=(10,4))
sns.countplot(x='month', data=df)
plt.title("Admissions per Month (Raw Epidemic Signal)")
plt.show()

leakage_cols = ['ID', 'Name', 'checkin date', 'checkout date']
df.drop(columns=[c for c in leakage_cols if c in df.columns], inplace=True)

df['CBC-TLC1'] = pd.to_numeric(df['CBC-TLC1'], errors='coerce')
df['CBC-TLC2'] = pd.to_numeric(df['CBC-TLC2'], errors='coerce')

df.drop_duplicates(inplace=True)

TARGET = 'Diagnosis'

df = df.dropna(subset=[TARGET])

y = df[TARGET]
X = df.drop(columns=[TARGET])

num_cols = X.select_dtypes(include=['int64', 'float64']).columns
cat_cols = X.select_dtypes(include='object').columns

for col in num_cols:
    low = X[col].quantile(0.01)
    high = X[col].quantile(0.99)
    X[col] = X[col].clip(low, high)

from sklearn.preprocessing import LabelEncoder

encoders = {}

for col in cat_cols:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    encoders[col] = le

print("X dtypes after Label Encoding:")
print(X.dtypes)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X[num_cols] = scaler.fit_transform(X[num_cols])

from sklearn.preprocessing import LabelEncoder

target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y)

print("\n✅ CLEAN DATA SUMMARY")
print("Shape:", df.shape)
print("Missing values:\n", df.isnull().sum().sum())
print("Target classes:", df['Diagnosis'].nunique())

plt.figure(figsize=(10,3))
sns.heatmap(X.isnull(), cbar=False)
plt.title("Missing Values After Cleaning")
plt.show()

plt.figure(figsize=(10,4))
sns.histplot(X['Age'], bins=30, kde=True)
plt.title("Age Distribution After Scaling")
plt.show()

plt.figure(figsize=(14,10))
sns.heatmap(
    pd.DataFrame(X).corr(),
    cmap='coolwarm',
    linewidths=0.3
)
plt.title("Feature Correlation Heatmap (After Cleaning)")
plt.show()

def normalize_diagnosis(text):
    if pd.isna(text):
        return "Unknown"

    text = text.lower()

    if any(x in text for x in ["kidney", "aki", "urea", "creatinine"]):
        return "Kidney Disease"
    elif any(x in text for x in ["liver", "hepatic"]):
        return "Liver Disease"
    elif any(x in text for x in ["stroke", "faint", "neuro"]):
        return "Neurological"
    elif any(x in text for x in ["heart", "cardiac"]):
        return "Cardiovascular"
    elif any(x in text for x in ["diabetes", "glucose"]):
        return "Diabetes"
    else:
        return "Other"

df["Diagnosis_Grouped"] = df["Diagnosis"].apply(normalize_diagnosis)

diagnosis_counts = df["Diagnosis_Grouped"].value_counts()

valid_classes = diagnosis_counts[diagnosis_counts >= 20].index

df = df[df["Diagnosis_Grouped"].isin(valid_classes)]

df["Risk_Diabetes"] = (
    (df["glucose"] >= 126) |
    (df["BMI"] >= 30) |
    (df["Has_Diabetes"] == 1)
).astype(int)

df["Risk_Heart"] = (
    (df["Systolic_BP(hypertention risk)"] >= 140) |
    (df["Has_Hypertension"] == 1) |
    (df["Has_Heart_Disease"] == 1)
).astype(int)

risk_features = [
    "Age", "Gender", "BMI", "glucose",
    "Systolic_BP(hypertention risk)",
    "avg_creatinine", "avg_urea",
    "avg_hb", "avg_tlc", "avg_platelets",
    "Smoking_Status", "Physical_Activity_Level"
]

X = df[risk_features]
y = df["Risk_Diabetes"]  # example

def diabetes_prevention_risk():
    return [
        "Reduce sugar intake",
        "Increase physical activity",
        "Regular glucose monitoring",
        "Weight management"
    ]

epidemic_df = df.groupby(
    ["month", "Diagnosis_Grouped"]
).size().reset_index(name="cases")

threshold = epidemic_df["cases"].quantile(0.75)

epidemic_df["Epidemic"] = (
    epidemic_df["cases"] >= threshold
).astype(int)

X = epidemic_df[["month", "cases"]]
y = epidemic_df["Epidemic"]

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Split the epidemic data into training and testing sets using distinct variable names
X_train_epi_old, X_test_epi_old, y_train_epi_old, y_test_epi_old = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

epi_model = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42
)

epi_model.fit(X_train_epi_old, y_train_epi_old)

print("Epidemic model trained using X_train_epi_old and y_train_epi_old.")

epidemic_df['cases_lag_1'] = epidemic_df.groupby('Diagnosis_Grouped')['cases'].shift(1)
epidemic_df['cases_lag_2'] = epidemic_df.groupby('Diagnosis_Grouped')['cases'].shift(2)
epidemic_df['cases_rolling_mean_3'] = epidemic_df.groupby('Diagnosis_Grouped')['cases'].rolling(3).mean().reset_index(0, drop=True)
epidemic_df['cases_rolling_std_3'] = epidemic_df.groupby('Diagnosis_Grouped')['cases'].rolling(3).std().reset_index(0, drop=True)
epidemic_df['month_sin'] = np.sin(2 * np.pi * epidemic_df['month'] / 12)
epidemic_df['month_cos'] = np.cos(2 * np.pi * epidemic_df['month'] / 12)

# Fill NaN values created by lag and rolling features
epidemic_df = epidemic_df.fillna(0)

# Define threshold for epidemic (75th percentile)
threshold = epidemic_df["cases"].quantile(0.75)
epidemic_df["Epidemic"] = (epidemic_df["cases"] >= threshold).astype(int)

# Select features
feature_cols = ['month', 'cases', 'cases_lag_1', 'cases_lag_2',
                'cases_rolling_mean_3', 'cases_rolling_std_3',
                'month_sin', 'month_cos']

X_epidemic = epidemic_df[feature_cols]
y_epidemic = epidemic_df["Epidemic"]

# Scale features
scaler = StandardScaler()
X_epidemic_scaled = scaler.fit_transform(X_epidemic)
X_epidemic_scaled = pd.DataFrame(X_epidemic_scaled, columns=feature_cols)

# Train-test split with stratification
X_train_epi, X_test_epi, y_train_epi, y_test_epi = train_test_split(
    X_epidemic_scaled, y_epidemic,
    test_size=0.2,
    random_state=42,
    stratify=y_epidemic
)

print("✅ Feature Engineering Complete")
print(f"X_train_epi shape: {X_train_epi.shape}")
print(f"X_test_epi shape: {X_test_epi.shape}")
print(f"Class distribution in training:\n{pd.Series(y_train_epi).value_counts()}")
print(f"Class distribution in testing:\n{pd.Series(y_test_epi).value_counts()}")

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import ConfusionMatrixDisplay # Added import

print("="*60)
print("MODEL 1B: RANDOM FOREST FOR EPIDEMIC PREDICTION")
print("="*60)

rf_epi_model = RandomForestClassifier(
    n_estimators=500,
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=2,
    max_features='sqrt',
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

rf_epi_model.fit(X_train_epi, y_train_epi)

rf_epi_preds = rf_epi_model.predict(X_test_epi)
rf_epi_proba = rf_epi_model.predict_proba(X_test_epi)[:, 1]

print("\n📊 Random Forest Classification Report:")
print(classification_report(y_test_epi, rf_epi_preds))

print("\n📈 Key Metrics:")
print(f"Accuracy: {accuracy_score(y_test_epi, rf_epi_preds):.4f}")
print(f"Precision: {precision_score(y_test_epi, rf_epi_preds, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test_epi, rf_epi_preds, average='weighted'):.4f}")
print(f"F1-Score: {f1_score(y_test_epi, rf_epi_preds, average='weighted'):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test_epi, rf_epi_proba):.4f}")

# Confusion Matrix
cm_rf = confusion_matrix(y_test_epi, rf_epi_preds, normalize="true")
plt.figure(figsize=(6,6))
disp = ConfusionMatrixDisplay(cm_rf)
disp.plot(cmap="Greens")
plt.title("Random Forest – Epidemic Prediction")
plt.show()

# Feature Importance
plt.figure(figsize=(10,6))
feature_importance_rf = pd.DataFrame({
    'feature': feature_cols,
    'importance': rf_epi_model.feature_importances_
}).sort_values('importance', ascending=False)
sns.barplot(data=feature_importance_rf, x='importance', y='feature')
plt.title("Random Forest Feature Importance for Epidemic Prediction")
plt.tight_layout()
plt.show()

from sklearn.linear_model import LogisticRegression

print("="*60)
print("MODEL 0: LOGISTIC REGRESSION (BASELINE)")
print("="*60)

lr_epi_model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced',
    solver='lbfgs',
    random_state=42
)

lr_epi_model.fit(X_train_epi, y_train_epi)

lr_epi_preds = lr_epi_model.predict(X_test_epi)
lr_epi_proba = lr_epi_model.predict_proba(X_test_epi)[:, 1]

print("\n📊 Logistic Regression Classification Report:")
print(classification_report(y_test_epi, lr_epi_preds))

print("\n📈 Key Metrics:")
print(f"Accuracy: {accuracy_score(y_test_epi, lr_epi_preds):.4f}")
print(f"Precision: {precision_score(y_test_epi, lr_epi_preds, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test_epi, lr_epi_preds, average='weighted'):.4f}")
print(f"F1-Score: {f1_score(y_test_epi, lr_epi_preds, average='weighted'):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test_epi, lr_epi_proba):.4f}")

print("\n💡 Note: Logistic Regression is a simple baseline model.")
print("   More complex models should perform better for epidemic prediction.")

# Confusion Matrix
cm_lr = confusion_matrix(y_test_epi, lr_epi_preds, normalize="true")
plt.figure(figsize=(6,6))
disp = ConfusionMatrixDisplay(cm_lr)
disp.plot(cmap="Reds")
plt.title("Logistic Regression – Epidemic Prediction (Baseline)")
plt.show()

from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

print("="*60)
print("MODEL 1: XGBOOST FOR EPIDEMIC PREDICTION")
print("="*60)

# Calculate scale_pos_weight for imbalanced classes
scale_pos_weight = len(y_train_epi[y_train_epi==0]) / len(y_train_epi[y_train_epi==1])

xgb_epi_model = XGBClassifier(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    eval_metric='logloss',
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    use_label_encoder=False
)

xgb_epi_model.fit(X_train_epi, y_train_epi)

xgb_epi_preds = xgb_epi_model.predict(X_test_epi)
xgb_epi_proba = xgb_epi_model.predict_proba(X_test_epi)[:, 1]

print("\n📊 XGBoost Classification Report:")
print(classification_report(y_test_epi, xgb_epi_preds))

print("\n📈 Key Metrics:")
print(f"Accuracy: {accuracy_score(y_test_epi, xgb_epi_preds):.4f}")
print(f"Precision: {precision_score(y_test_epi, xgb_epi_preds, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test_epi, xgb_epi_preds, average='weighted'):.4f}")
print(f"F1-Score: {f1_score(y_test_epi, xgb_epi_preds, average='weighted'):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test_epi, xgb_epi_proba):.4f}")

# Confusion Matrix
cm_xgb = confusion_matrix(y_test_epi, xgb_epi_preds, normalize="true")
plt.figure(figsize=(6,6))
disp = ConfusionMatrixDisplay(cm_xgb)
disp.plot(cmap="Purples")
plt.title("XGBoost – Epidemic Prediction")
plt.show()

# Feature Importance
plt.figure(figsize=(10,6))
feature_importance = pd.DataFrame({
    'feature': feature_cols,
    'importance': xgb_epi_model.feature_importances_
}).sort_values('importance', ascending=False)
sns.barplot(data=feature_importance, x='importance', y='feature')
plt.title("XGBoost Feature Importance for Epidemic Prediction")
plt.tight_layout()
plt.show()

from lightgbm import LGBMClassifier
import warnings
warnings.filterwarnings('ignore', category=UserWarning)

print("="*60)
print("MODEL 2: LIGHTGBM FOR EPIDEMIC PREDICTION")
print("="*60)

lgbm_epi_model = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=7,
    num_leaves=31,
    min_child_samples=20,
    subsample=0.8,
    colsample_bytree=0.8,
    class_weight='balanced',
    random_state=42,
    verbose=-1
)

lgbm_epi_model.fit(X_train_epi, y_train_epi)

lgbm_epi_preds = lgbm_epi_model.predict(X_test_epi)
lgbm_epi_proba = lgbm_epi_model.predict_proba(X_test_epi)[:, 1]

print("\n📊 LightGBM Classification Report:")
print(classification_report(y_test_epi, lgbm_epi_preds))

print("\n📈 Key Metrics:")
print(f"Accuracy: {accuracy_score(y_test_epi, lgbm_epi_preds):.4f}")
print(f"Precision: {precision_score(y_test_epi, lgbm_epi_preds, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test_epi, lgbm_epi_preds, average='weighted'):.4f}")
print(f"F1-Score: {f1_score(y_test_epi, lgbm_epi_preds, average='weighted'):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test_epi, lgbm_epi_proba):.4f}")

# Confusion Matrix
cm_lgbm = confusion_matrix(y_test_epi, lgbm_epi_preds, normalize="true")
plt.figure(figsize=(6,6))
disp = ConfusionMatrixDisplay(cm_lgbm)
disp.plot(cmap="Greens")
plt.title("LightGBM – Epidemic Prediction")
plt.show()

#pip install catboost
from catboost import CatBoostClassifier

print("="*60)
print("MODEL 3: CATBOOST FOR EPIDEMIC PREDICTION")
print("="*60)

catboost_epi_model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=6,
    l2_leaf_reg=3,
    border_count=128,
    auto_class_weights='Balanced',
    random_seed=42,
    verbose=False
)

catboost_epi_model.fit(X_train_epi, y_train_epi)

catboost_epi_preds = catboost_epi_model.predict(X_test_epi)
catboost_epi_proba = catboost_epi_model.predict_proba(X_test_epi)[:, 1]

print("\n📊 CatBoost Classification Report:")
print(classification_report(y_test_epi, catboost_epi_preds))

print("\n📈 Key Metrics:")
print(f"Accuracy: {accuracy_score(y_test_epi, catboost_epi_preds):.4f}")
print(f"Precision: {precision_score(y_test_epi, catboost_epi_preds, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test_epi, catboost_epi_preds, average='weighted'):.4f}")
print(f"F1-Score: {f1_score(y_test_epi, catboost_epi_preds, average='weighted'):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test_epi, catboost_epi_proba):.4f}")

# Confusion Matrix
cm_catboost = confusion_matrix(y_test_epi, catboost_epi_preds, normalize="true")
plt.figure(figsize=(6,6))
disp = ConfusionMatrixDisplay(cm_catboost)
disp.plot(cmap="Oranges")
plt.title("CatBoost – Epidemic Prediction")
plt.show()

from sklearn.ensemble import GradientBoostingClassifier

print("="*60)
print("MODEL 3B: GRADIENT BOOSTING FOR EPIDEMIC PREDICTION")
print("="*60)

gb_epi_model = GradientBoostingClassifier(
    n_estimators=400,
    learning_rate=0.1,
    max_depth=5,
    min_samples_split=10,
    min_samples_leaf=5,
    subsample=0.8,
    max_features='sqrt',
    random_state=42
)

gb_epi_model.fit(X_train_epi, y_train_epi)

gb_epi_preds = gb_epi_model.predict(X_test_epi)
gb_epi_proba = gb_epi_model.predict_proba(X_test_epi)[:, 1]

print("\n📊 Gradient Boosting Classification Report:")
print(classification_report(y_test_epi, gb_epi_preds))

print("\n📈 Key Metrics:")
print(f"Accuracy: {accuracy_score(y_test_epi, gb_epi_preds):.4f}")
print(f"Precision: {precision_score(y_test_epi, gb_epi_preds, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test_epi, gb_epi_preds, average='weighted'):.4f}")
print(f"F1-Score: {f1_score(y_test_epi, gb_epi_preds, average='weighted'):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test_epi, gb_epi_proba):.4f}")

# Confusion Matrix
cm_gb = confusion_matrix(y_test_epi, gb_epi_preds, normalize="true")
plt.figure(figsize=(6,6))
disp = ConfusionMatrixDisplay(cm_gb)
disp.plot(cmap="Blues")
plt.title("Gradient Boosting – Epidemic Prediction")
plt.show()

from sklearn.ensemble import VotingClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression

print("="*60)
print("MODEL 7: VOTING ENSEMBLE")
print("="*60)

# Voting Ensemble (combines predictions from all models)
voting_model = VotingClassifier(
    estimators=[
        ('rf', rf_epi_model),
        ('xgb', xgb_epi_model),
        ('gb', gb_epi_model),
        ('lgbm', lgbm_epi_model),
        ('catboost', catboost_epi_model)
    ],
    voting='soft'
)

voting_model.fit(X_train_epi, y_train_epi)

voting_preds = voting_model.predict(X_test_epi)
voting_proba = voting_model.predict_proba(X_test_epi)[:, 1]

print("\n📊 Voting Ensemble Classification Report:")
print(classification_report(y_test_epi, voting_preds))

print("\n📈 Key Metrics:")
print(f"Accuracy: {accuracy_score(y_test_epi, voting_preds):.4f}")
print(f"Precision: {precision_score(y_test_epi, voting_preds, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test_epi, voting_preds, average='weighted'):.4f}")
print(f"F1-Score: {f1_score(y_test_epi, voting_preds, average='weighted'):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test_epi, voting_proba):.4f}")

# Confusion Matrix
cm_voting = confusion_matrix(y_test_epi, voting_preds, normalize="true")
plt.figure(figsize=(6,6))
disp = ConfusionMatrixDisplay(cm_voting)
disp.plot(cmap="RdPu")
plt.title("Voting Ensemble – Epidemic Prediction")
plt.show()

print("\n" + "="*60)
print("MODEL 8: STACKING ENSEMBLE")
print("="*60)

# Stacking Ensemble (uses meta-learner on top of base models)
stacking_model = StackingClassifier(
    estimators=[
        ('rf', rf_epi_model),
        ('xgb', xgb_epi_model),
        ('gb', gb_epi_model),
        ('lgbm', lgbm_epi_model),
        ('catboost', catboost_epi_model)
    ],
    final_estimator=LogisticRegression(max_iter=1000, class_weight='balanced'),
    cv=5
)

stacking_model.fit(X_train_epi, y_train_epi)

stacking_preds = stacking_model.predict(X_test_epi)
stacking_proba = stacking_model.predict_proba(X_test_epi)[:, 1]

print("\n📊 Stacking Ensemble Classification Report:")
print(classification_report(y_test_epi, stacking_preds))

print("\n📈 Key Metrics:")
print(f"Accuracy: {accuracy_score(y_test_epi, stacking_preds):.4f}")
print(f"Precision: {precision_score(y_test_epi, stacking_preds, average='weighted'):.4f}")
print(f"Recall: {recall_score(y_test_epi, stacking_preds, average='weighted'):.4f}")
print(f"F1-Score: {f1_score(y_test_epi, stacking_preds, average='weighted'):.4f}")
print(f"ROC-AUC: {roc_auc_score(y_test_epi, stacking_proba):.4f}")

# Confusion Matrix
cm_stacking = confusion_matrix(y_test_epi, stacking_preds, normalize="true")
plt.figure(figsize=(6,6))
disp = ConfusionMatrixDisplay(cm_stacking)
disp.plot(cmap="YlOrRd")
plt.title("Stacking Ensemble – Epidemic Prediction")
plt.show()

print("="*60)
print("MODEL COMPARISON FOR EPIDEMIC PREDICTION")
print("="*60)

# Create comparison dataframe with ALL 8 models
models_comparison = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest', 'XGBoost', 'Gradient Boosting',
              'LightGBM', 'CatBoost', 'Voting Ensemble', 'Stacking Ensemble'],
    'Accuracy': [
        accuracy_score(y_test_epi, lr_epi_preds),
        accuracy_score(y_test_epi, rf_epi_preds),
        accuracy_score(y_test_epi, xgb_epi_preds),
        accuracy_score(y_test_epi, gb_epi_preds),
        accuracy_score(y_test_epi, lgbm_epi_preds),
        accuracy_score(y_test_epi, catboost_epi_preds),
        accuracy_score(y_test_epi, voting_preds),
        accuracy_score(y_test_epi, stacking_preds)
    ],
    'Precision': [
        precision_score(y_test_epi, lr_epi_preds, average='weighted'),
        precision_score(y_test_epi, rf_epi_preds, average='weighted'),
        precision_score(y_test_epi, xgb_epi_preds, average='weighted'),
        precision_score(y_test_epi, gb_epi_preds, average='weighted'),
        precision_score(y_test_epi, lgbm_epi_preds, average='weighted'),
        precision_score(y_test_epi, catboost_epi_preds, average='weighted'),
        precision_score(y_test_epi, voting_preds, average='weighted'),
        precision_score(y_test_epi, stacking_preds, average='weighted')
    ],
    'Recall': [
        recall_score(y_test_epi, lr_epi_preds, average='weighted'),
        recall_score(y_test_epi, rf_epi_preds, average='weighted'),
        recall_score(y_test_epi, xgb_epi_preds, average='weighted'),
        recall_score(y_test_epi, gb_epi_preds, average='weighted'),
        recall_score(y_test_epi, lgbm_epi_preds, average='weighted'),
        recall_score(y_test_epi, catboost_epi_preds, average='weighted'),
        recall_score(y_test_epi, voting_preds, average='weighted'),
        recall_score(y_test_epi, stacking_preds, average='weighted')
    ],
    'F1-Score': [
        f1_score(y_test_epi, lr_epi_preds, average='weighted'),
        f1_score(y_test_epi, rf_epi_preds, average='weighted'),
        f1_score(y_test_epi, xgb_epi_preds, average='weighted'),
        f1_score(y_test_epi, gb_epi_preds, average='weighted'),
        f1_score(y_test_epi, lgbm_epi_preds, average='weighted'),
        f1_score(y_test_epi, catboost_epi_preds, average='weighted'),
        f1_score(y_test_epi, voting_preds, average='weighted'),
        f1_score(y_test_epi, stacking_preds, average='weighted')
    ],
    'ROC-AUC': [
        roc_auc_score(y_test_epi, lr_epi_proba),
        roc_auc_score(y_test_epi, rf_epi_proba),
        roc_auc_score(y_test_epi, xgb_epi_proba),
        roc_auc_score(y_test_epi, gb_epi_proba),
        roc_auc_score(y_test_epi, lgbm_epi_proba),
        roc_auc_score(y_test_epi, catboost_epi_proba),
        roc_auc_score(y_test_epi, voting_proba),
        roc_auc_score(y_test_epi, stacking_proba)
    ]
})

# Sort by F1-Score (most important for medical applications)
models_comparison = models_comparison.sort_values('F1-Score', ascending=False)
print("\n All Models Ranked by F1-Score:")
print(models_comparison.to_string(index=False))

# Create a styled dataframe highlighting the best model
print("\n" + "="*60)
best_f1_model = models_comparison.iloc[0]
print(f" BEST MODEL (by F1-Score): {best_f1_model['Model']}")
print(f"   F1-Score: {best_f1_model['F1-Score']:.4f}")
print(f"   ROC-AUC: {best_f1_model['ROC-AUC']:.4f}")
print(f"   Recall: {best_f1_model['Recall']:.4f}")

# Also show best by ROC-AUC
models_by_roc = models_comparison.sort_values('ROC-AUC', ascending=False)
best_roc_model = models_by_roc.iloc[0]
print(f"\n BEST MODEL (by ROC-AUC): {best_roc_model['Model']}")
print(f"   ROC-AUC: {best_roc_model['ROC-AUC']:.4f}")
print(f"   F1-Score: {best_roc_model['F1-Score']:.4f}")
print("="*60)

# Comprehensive Visualization
fig, axes = plt.subplots(2, 3, figsize=(18, 10))

# Sort by F1-Score for consistent visualization
models_comparison_sorted = models_comparison.sort_values('F1-Score', ascending=True)

# Plot 1: Accuracy
axes[0, 0].barh(models_comparison_sorted['Model'], models_comparison_sorted['Accuracy'], color='#2E86AB')
axes[0, 0].set_xlabel('Accuracy', fontsize=11, fontweight='bold')
axes[0, 0].set_title('Model Accuracy Comparison', fontsize=12, fontweight='bold')
axes[0, 0].set_xlim(0, 1)
axes[0, 0].axvline(x=0.85, color='red', linestyle='--', alpha=0.7, label='Target (0.85)')
axes[0, 0].legend()
axes[0, 0].grid(axis='x', alpha=0.3)

# Plot 2: Precision
axes[0, 1].barh(models_comparison_sorted['Model'], models_comparison_sorted['Precision'], color='#A23B72')
axes[0, 1].set_xlabel('Precision', fontsize=11, fontweight='bold')
axes[0, 1].set_title('Model Precision Comparison', fontsize=12, fontweight='bold')
axes[0, 1].set_xlim(0, 1)
axes[0, 1].axvline(x=0.80, color='red', linestyle='--', alpha=0.7, label='Target (0.80)')
axes[0, 1].legend()
axes[0, 1].grid(axis='x', alpha=0.3)

# Plot 3: Recall
axes[0, 2].barh(models_comparison_sorted['Model'], models_comparison_sorted['Recall'], color='#F18F01')
axes[0, 2].set_xlabel('Recall', fontsize=11, fontweight='bold')
axes[0, 2].set_title('Model Recall Comparison', fontsize=12, fontweight='bold')
axes[0, 2].set_xlim(0, 1)
axes[0, 2].axvline(x=0.85, color='red', linestyle='--', alpha=0.7, label='Target (0.85)')
axes[0, 2].legend()
axes[0, 2].grid(axis='x', alpha=0.3)

# Plot 4: F1-Score (MOST IMPORTANT)
bars = axes[1, 0].barh(models_comparison_sorted['Model'], models_comparison_sorted['F1-Score'], color='#06A77D')
axes[1, 0].set_xlabel('F1-Score', fontsize=11, fontweight='bold')
axes[1, 0].set_title('⭐ F1-Score Comparison (PRIMARY METRIC) ⭐', fontsize=12, fontweight='bold')
axes[1, 0].set_xlim(0, 1)
axes[1, 0].axvline(x=0.85, color='red', linestyle='--', linewidth=2, alpha=0.7, label='Good (0.85)')
axes[1, 0].axvline(x=0.90, color='darkred', linestyle='--', linewidth=2, alpha=0.7, label='Excellent (0.90)')
axes[1, 0].legend()
axes[1, 0].grid(axis='x', alpha=0.3)
# Highlight the best model
best_idx = list(models_comparison_sorted['Model']).index(best_f1_model['Model'])
bars[best_idx].set_color('#FFD700')

# Plot 5: ROC-AUC
bars_roc = axes[1, 1].barh(models_comparison_sorted['Model'], models_comparison_sorted['ROC-AUC'], color='#C73E1D')
axes[1, 1].set_xlabel('ROC-AUC', fontsize=11, fontweight='bold')
axes[1, 1].set_title('⭐ ROC-AUC Comparison (SECONDARY METRIC) ⭐', fontsize=12, fontweight='bold')
axes[1, 1].set_xlim(0, 1)
axes[1, 1].axvline(x=0.90, color='red', linestyle='--', linewidth=2, alpha=0.7, label='Good (0.90)')
axes[1, 1].axvline(x=0.95, color='darkred', linestyle='--', linewidth=2, alpha=0.7, label='Excellent (0.95)')
axes[1, 1].legend()
axes[1, 1].grid(axis='x', alpha=0.3)
# Highlight the best model
best_roc_idx = list(models_comparison_sorted['Model']).index(best_roc_model['Model'])
bars_roc[best_roc_idx].set_color('#FFD700')

# Plot 6: All Metrics Radar Chart for Top 3
from math import pi

top3_models = models_comparison.head(3)
categories = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC']
N = len(categories)

angles = [n / float(N) * 2 * pi for n in range(N)]
angles += angles[:1]

ax = plt.subplot(2, 3, 6, projection='polar')
colors = ['#2E86AB', '#A23B72', '#F18F01']

for idx, (_, row) in enumerate(top3_models.iterrows()):
    values = [row['Accuracy'], row['Precision'], row['Recall'], row['F1-Score'], row['ROC-AUC']]
    values += values[:1]
    ax.plot(angles, values, 'o-', linewidth=2, label=row['Model'], color=colors[idx])
    ax.fill(angles, values, alpha=0.15, color=colors[idx])

ax.set_xticks(angles[:-1])
ax.set_xticklabels(categories, size=9)
ax.set_ylim(0, 1)
ax.set_title('Top 3 Models - All Metrics', fontsize=12, fontweight='bold', pad=20)
ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1))
ax.grid(True)

plt.tight_layout()
plt.show()

# Additional: Model Type Comparison
print("\n" + "="*60)
print(" MODEL CATEGORIES COMPARISON")
print("="*60)

baseline_models = models_comparison[models_comparison['Model'].isin(['Logistic Regression'])]
tree_models = models_comparison[models_comparison['Model'].isin(['Random Forest', 'XGBoost', 'Gradient Boosting', 'LightGBM', 'CatBoost'])]
ensemble_models = models_comparison[models_comparison['Model'].isin(['Voting Ensemble', 'Stacking Ensemble'])]

print("\n📌 Baseline Model:")
print(baseline_models[['Model', 'F1-Score', 'ROC-AUC']].to_string(index=False))

print("\n🌲 Tree-Based Models (Top 3):")
print(tree_models.head(3)[['Model', 'F1-Score', 'ROC-AUC']].to_string(index=False))

print("\n🎯 Ensemble Models:")
print(ensemble_models[['Model', 'F1-Score', 'ROC-AUC']].to_string(index=False))

########epidemic output

# CELL 6: Epidemic Data Preparation
# Aggregate cases by month and diagnosis
epidemic_df = df.groupby(
    ["month", "Diagnosis_Grouped"]
).size().reset_index(name="cases")

# Visualize disease trends
plt.figure(figsize=(10,6))
sns.lineplot(
    data=epidemic_df,
    x="month",
    y="cases",
    hue="Diagnosis_Grouped"
)
plt.title("Disease Trends Over Time")
plt.xlabel("Month")
plt.ylabel("Number of Cases")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

print("✅ Epidemic data aggregated by month and diagnosis!")
print(f"\nEpidemic dataframe shape: {epidemic_df.shape}")
epidemic_df.head(10)

# CELL 7: Feature Engineering for Epidemic Prediction
# Create lag features
epidemic_df['cases_lag_1'] = epidemic_df.groupby('Diagnosis_Grouped')['cases'].shift(1)
epidemic_df['cases_lag_2'] = epidemic_df.groupby('Diagnosis_Grouped')['cases'].shift(2)

# Create rolling features
epidemic_df['cases_rolling_mean_3'] = epidemic_df.groupby('Diagnosis_Grouped')['cases'].rolling(3).mean().reset_index(0, drop=True)
epidemic_df['cases_rolling_std_3'] = epidemic_df.groupby('Diagnosis_Grouped')['cases'].rolling(3).std().reset_index(0, drop=True)

# Create cyclical features for month
epidemic_df['month_sin'] = np.sin(2 * np.pi * epidemic_df['month'] / 12)
epidemic_df['month_cos'] = np.cos(2 * np.pi * epidemic_df['month'] / 12)

# Fill NaN values
epidemic_df = epidemic_df.fillna(0)

feature_cols = ['month', 'cases', 'cases_lag_1', 'cases_lag_2',
                'cases_rolling_mean_3', 'cases_rolling_std_3',
                'month_sin', 'month_cos',
                'Diagnosis_Encoded']

# Define epidemic threshold (75th percentile)
threshold = epidemic_df["cases"].quantile(0.75)
epidemic_df["Epidemic"] = (epidemic_df["cases"] >= threshold).astype(int)

print("✅ Feature engineering completed!")
print(f"Epidemic threshold: {threshold:.2f} cases")
print(f"\nEpidemic distribution:")
print(epidemic_df["Epidemic"].value_counts())
epidemic_df.head(10)

# CELL 9: 🚨 GENERATE HOSPITAL EPIDEMIC ALERTS 🚨
# This generates the actual output messages for the hospital

# Get predictions with probabilities
y_pred_proba_epi = rf_epi_model.predict_proba(X_test_epi)
y_pred_epi = rf_epi_model.predict(X_test_epi)

# Create results dataframe
test_indices = X_test_epi.index
results_df = epidemic_df.loc[test_indices].copy()
results_df['Predicted_Epidemic'] = y_pred_epi
results_df['Epidemic_Probability'] = y_pred_proba_epi[:, 1]  # Probability of epidemic

# Filter high-risk predictions (epidemic alerts)
epidemic_alerts = results_df[results_df['Predicted_Epidemic'] == 1].copy()
epidemic_alerts = epidemic_alerts.sort_values('Epidemic_Probability', ascending=False)

print("🏥 HOSPITAL EPIDEMIC ALERT SYSTEM")
print("=" * 80)
print(f"\n📊 Total predictions made: {len(results_df)}")
print(f"⚠️  Epidemic alerts detected: {len(epidemic_alerts)}")
print(f"✅ Normal conditions: {len(results_df) - len(epidemic_alerts)}")
print("\n" + "=" * 80)

if len(epidemic_alerts) > 0:
    print("\n🚨 URGENT EPIDEMIC ALERTS FOR HOSPITAL:")
    print("=" * 80)

    for idx, row in epidemic_alerts.iterrows():
        month_num = int(row['month'])
        month_names = {1: 'January', 2: 'February', 3: 'March', 4: 'April',
                      5: 'May', 6: 'June', 7: 'July', 8: 'August',
                      9: 'September', 10: 'October', 11: 'November', 12: 'December'}

        print(f"\n📅 Alert for: {month_names[month_num]}")
        print(f"🦠 Disease Category: {row['Diagnosis_Grouped']}")
        print(f"📈 Expected Cases: {int(row['cases'])}")
        print(f"⚠️  Epidemic Probability: {row['Epidemic_Probability']:.1%}")
        print(f"🎯 Confidence Level: {'HIGH' if row['Epidemic_Probability'] > 0.7 else 'MODERATE'}")
        print("-" * 80)

    print("\n💊 RECOMMENDED ACTIONS:")
    print("✓ Increase stock of relevant medications")
    print("✓ Prepare additional ICU beds")
    print("✓ Schedule extra medical staff")
    print("✓ Coordinate with pharmacy and lab departments")
    print("✓ Set up early screening protocols")
else:
    print("\n✅ No epidemic alerts detected in test period")
    print("Current disease burden is within normal parameters")

print("\n" + "=" * 80)

# Save results to CSV for hospital system integration
epidemic_alerts.to_csv('hospital_epidemic_alerts.csv', index=False)
print("\n💾 Results saved to: hospital_epidemic_alerts.csv")

# Display detailed results table
print("\n📋 DETAILED EPIDEMIC ALERTS TABLE:")
if len(epidemic_alerts) > 0:
    display_cols = ['month', 'Diagnosis_Grouped', 'cases', 'Epidemic_Probability', 'Predicted_Epidemic']
    print(epidemic_alerts[display_cols].to_string(index=False))

plt.figure(figsize=(10,4))
sns.countplot(x='month', data=df)
plt.title("Admissions per Month (Raw Epidemic Signal)")
plt.show()

#####

TARGET = 'Diagnosis_Grouped'
y = df[TARGET]
X = df.drop(columns=[TARGET, 'Diagnosis', 'Risk_Diabetes', 'Risk_Heart'], errors='ignore')

print(f"Target variable set to: {TARGET}")
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

num_cols = X.select_dtypes(include=['int64', 'float64']).columns
cat_cols = X.select_dtypes(include='object').columns

print(f"Numerical columns: {num_cols.tolist()}")
print(f"Categorical columns: {cat_cols.tolist()}")

num_imputer = SimpleImputer(strategy='median')
X[num_cols] = num_imputer.fit_transform(X[num_cols])

cat_imputer = SimpleImputer(strategy='most_frequent')
X[cat_cols] = cat_imputer.fit_transform(X[cat_cols])

print("Missing values imputed for numerical and categorical columns in X.")

X = df[risk_features].copy() # Explicitly create a copy
y = df["Risk_Diabetes"]

print("Shape of X for Risk_Diabetes task:", X.shape)
print("Shape of y for Risk_Diabetes task:", y.shape)

num_cols_risk = X.select_dtypes(include=['int64', 'float64']).columns
cat_cols_risk = X.select_dtypes(include='object').columns

print(f"Numerical columns for Risk_Diabetes task: {num_cols_risk.tolist()}")
print(f"Categorical columns for Risk_Diabetes task: {cat_cols_risk.tolist()}")

from sklearn.impute import SimpleImputer

num_imputer_risk = SimpleImputer(strategy='median')
X[num_cols_risk] = num_imputer_risk.fit_transform(X[num_cols_risk])

cat_imputer_risk = SimpleImputer(strategy='most_frequent')
X[cat_cols_risk] = cat_imputer_risk.fit_transform(X[cat_cols_risk])

print("Missing values imputed for numerical and categorical columns in X for risk prediction task.")

for col in num_cols_risk:
    low = X[col].quantile(0.01)
    high = X[col].quantile(0.99)
    X[col] = X[col].clip(low, high)

print("Outliers clipped for numerical columns in X for risk prediction task.")

num_cols_risk = X.select_dtypes(include=['int64', 'float64']).columns
cat_cols_risk = X.select_dtypes(include='object').columns

print(f"Numerical columns for Risk_Diabetes task: {num_cols_risk.tolist()}")
print(f"Categorical columns for Risk_Diabetes task: {cat_cols_risk.tolist()}")

num_imputer_risk = SimpleImputer(strategy='median')
X[num_cols_risk] = num_imputer_risk.fit_transform(X[num_cols_risk])

cat_imputer_risk = SimpleImputer(strategy='most_frequent')
X[cat_cols_risk] = cat_imputer_risk.fit_transform(X[cat_cols_risk])

print("Missing values imputed for numerical and categorical columns in X for risk prediction task.")

for col in num_cols_risk:
    low = X[col].quantile(0.01)
    high = X[col].quantile(0.99)
    X[col] = X[col].clip(low, high)

print("Outliers clipped for numerical columns in X for risk prediction task.")

from sklearn.preprocessing import LabelEncoder

risk_encoders = {}

for col in cat_cols_risk:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    risk_encoders[col] = le

print("Categorical columns in X for risk prediction task have been Label Encoded.")

from sklearn.preprocessing import StandardScaler

risk_scaler = StandardScaler()
X[num_cols_risk] = risk_scaler.fit_transform(X[num_cols_risk])

print("Numerical columns in X for risk prediction task have been scaled using StandardScaler.")

##########3

print("\n" + "=" * 70)
print("DATA PREPROCESSING")
print("=" * 70)

# Remove rows with missing diagnosis
df_clean = df.dropna(subset=['Diagnosis']).copy()
print(f"\nAfter removing missing diagnoses: {len(df_clean)} patients")

# Fill missing Age with median
df_clean['Age'].fillna(df_clean['Age'].median(), inplace=True)

# Fill missing numerical features with median
numerical_cols = ['CBC-HB1', 'CBC-TLC1', 'CBC-PLAT1', 'BLOOD-URIA1', 'BLOOD-creatinine1',
                  'CBC-HB2', 'CBC-TLC2', 'CBC-PLAT2', 'BLOOD-URIA2', 'BLOOD-creatinine2']

for col in numerical_cols:
    if col in df_clean.columns:
        df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')
        df_clean[col].fillna(df_clean[col].median(), inplace=True)

print("✓ Missing values handled")

print("\n" + "=" * 70)
print("FEATURE ENGINEERING")
print("=" * 70)

# Risk indicators with multiple severity levels
df_clean['Anemia_Risk'] = ((df_clean['avg_hb'] < 12).astype(int))
df_clean['Severe_Anemia'] = ((df_clean['avg_hb'] < 10).astype(int))

df_clean['Kidney_Dysfunction_Risk'] = ((df_clean['avg_creatinine'] > 1.3).astype(int))
df_clean['Severe_Kidney_Risk'] = ((df_clean['avg_creatinine'] > 2.0).astype(int))

df_clean['Diabetes_Risk'] = ((df_clean['glucose'] > 126).astype(int))
df_clean['Severe_Diabetes_Risk'] = ((df_clean['glucose'] > 180).astype(int))

df_clean['Hypertension_Risk'] = ((df_clean['Systolic_BP(hypertention risk)'] > 140).astype(int))
df_clean['Severe_Hypertension'] = ((df_clean['Systolic_BP(hypertention risk)'] > 160).astype(int))

df_clean['Platelet_Low'] = ((df_clean['avg_platelets'] < 150).astype(int))
df_clean['Platelet_High'] = ((df_clean['avg_platelets'] > 400).astype(int))

df_clean['High_Urea'] = ((df_clean['avg_urea'] > 40).astype(int))
df_clean['Severe_Urea'] = ((df_clean['avg_urea'] > 80).astype(int))

df_clean['Obesity_Risk'] = ((df_clean['BMI'] > 30).astype(int))
df_clean['Underweight'] = ((df_clean['BMI'] < 18.5).astype(int))

# Comorbidity features
df_clean['Comorbidity_Count'] = (df_clean['Has_Diabetes'] +
                                  df_clean['Has_Hypertension'] +
                                  df_clean['Has_Kidney_Disease'] +
                                  df_clean['Has_Heart_Disease'])

df_clean['Multiple_Comorbidities'] = (df_clean['Comorbidity_Count'] >= 2).astype(int)

# Medical ratios
df_clean['Creatinine_to_Urea_Ratio'] = df_clean['avg_creatinine'] / (df_clean['avg_urea'] + 0.01)
df_clean['Glucose_to_BMI_Ratio'] = df_clean['glucose'] / (df_clean['BMI'] + 0.01)
df_clean['HB_to_Platelet_Ratio'] = df_clean['avg_hb'] / (df_clean['avg_platelets'] + 1)

# Hospitalization patterns
df_clean['Long_Stay'] = (df_clean['Length_of_Stay'] > 7).astype(int)
df_clean['Very_Long_Stay'] = (df_clean['Length_of_Stay'] > 14).astype(int)
df_clean['Frequent_Admissions'] = (df_clean['admission count'] > 2).astype(int)

print("✓ Enhanced features created")

print("\n" + "=" * 70)
print("DISEASE CATEGORIZATION")
print("=" * 70)

def categorize_diagnosis(diagnosis):
    """Simplified categorization with clear boundaries"""
    if pd.isna(diagnosis):
        return 'Unknown'

    diagnosis = str(diagnosis).lower()

    # Main disease categories
    if 'diabet' in diagnosis or 'dka' in diagnosis:
        return 'Diabetes'
    elif 'kidney' in diagnosis or 'renal' in diagnosis or 'aki' in diagnosis or 'ckd' in diagnosis:
        return 'Kidney_Disease'
    elif 'stroke' in diagnosis or 'cerebrovascular' in diagnosis:
        return 'Stroke'
    elif 'heart' in diagnosis or 'cardiac' in diagnosis or 'chf' in diagnosis or 'myocardial' in diagnosis:
        return 'Heart_Disease'
    elif 'sepsis' in diagnosis or 'septic' in diagnosis:
        return 'Infection'
    elif 'pneumonia' in diagnosis or 'lung infection' in diagnosis:
        return 'Pneumonia'
    elif 'infection' in diagnosis or 'uti' in diagnosis:
        return 'Infection'
    elif 'hypertension' in diagnosis or 'high blood pressure' in diagnosis:
        return 'Hypertension'
    elif 'anemia' in diagnosis or 'animia' in diagnosis:
        return 'Anemia'
    elif 'hepatic' in diagnosis or 'liver' in diagnosis or 'cirrhosis' in diagnosis:
        return 'Liver_Disease'
    elif 'pulmonary' in diagnosis or 'respiratory' in diagnosis or 'hypoxia' in diagnosis:
        return 'Respiratory'
    else:
        return 'Other'

df_clean['Disease_Category'] = df_clean['Diagnosis'].apply(categorize_diagnosis)

print("Disease Category Distribution:")
print(df_clean['Disease_Category'].value_counts())

# Keep classes with at least 20 samples for good training
class_counts = df_clean['Disease_Category'].value_counts()
valid_classes = class_counts[class_counts >= 20].index.tolist()
df_clean = df_clean[df_clean['Disease_Category'].isin(valid_classes)].copy()

print(f"\nAfter filtering: {len(df_clean)} patients")
print(f"Number of disease categories: {df_clean['Disease_Category'].nunique()}")
print("\nFinal distribution:")
print(df_clean['Disease_Category'].value_counts())

print("\n" + "=" * 70)
print("FEATURE PREPARATION")
print("=" * 70)

feature_columns = [
    # Core medical features
    'Age', 'BMI', 'glucose', 'Systolic_BP(hypertention risk)',
    'avg_creatinine', 'avg_urea', 'avg_hb', 'avg_tlc', 'avg_platelets',
    'admission count', 'Length_of_Stay',

    # Existing conditions
    'Has_Diabetes', 'Has_Hypertension', 'Has_Kidney_Disease', 'Has_Heart_Disease',

    # Risk indicators
    'Anemia_Risk', 'Severe_Anemia',
    'Kidney_Dysfunction_Risk', 'Severe_Kidney_Risk',
    'Diabetes_Risk', 'Severe_Diabetes_Risk',
    'Hypertension_Risk', 'Severe_Hypertension',
    'Platelet_Low', 'Platelet_High',
    'High_Urea', 'Severe_Urea',
    'Obesity_Risk', 'Underweight',
    'Comorbidity_Count', 'Multiple_Comorbidities',

    # Derived features
    'Creatinine_to_Urea_Ratio', 'Glucose_to_BMI_Ratio', 'HB_to_Platelet_Ratio',
    'Long_Stay', 'Very_Long_Stay', 'Frequent_Admissions'
]

# Encode categorical features
le_gender = LabelEncoder()
df_clean['Gender_Encoded'] = le_gender.fit_transform(df_clean['Gender'])

le_smoking = LabelEncoder()
df_clean['Smoking_Encoded'] = le_smoking.fit_transform(df_clean['Smoking_Status'])

le_activity = LabelEncoder()
df_clean['Activity_Encoded'] = le_activity.fit_transform(df_clean['Physical_Activity_Level'])

feature_columns.extend(['Gender_Encoded', 'Smoking_Encoded', 'Activity_Encoded'])

# Prepare X and y
X = df_clean[feature_columns].copy()
y = df_clean['Disease_Category'].copy()

# Encode target
le_target = LabelEncoder()
y_encoded = le_target.fit_transform(y)

print(f"✓ Features: {len(feature_columns)}")
print(f"✓ Classes: {list(le_target.classes_)}")
print(f"✓ Total samples: {len(X)}")

print("\n" + "=" * 70)
print("DATA SPLITTING")
print("=" * 70)

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

print(f"Training set: {X_train.shape[0]} patients")
print(f"Testing set: {X_test.shape[0]} patients")

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\n✓ Data ready for training")
results = {}

print("\n" + "=" * 70)
print("MODEL 1: LOGISTIC REGRESSION")
print("=" * 70)

lr_model = LogisticRegression(max_iter=2000, random_state=42, class_weight='balanced')
lr_model.fit(X_train_scaled, y_train)

y_pred_test_lr = lr_model.predict(X_test_scaled)

test_acc_lr = accuracy_score(y_test, y_pred_test_lr)
f1_lr = f1_score(y_test, y_pred_test_lr, average='weighted')
precision_lr = precision_score(y_test, y_pred_test_lr, average='weighted', zero_division=0)
recall_lr = recall_score(y_test, y_pred_test_lr, average='weighted')

print(f"\n📊 Performance:")
print(f"   Test Accuracy:  {test_acc_lr:.4f} ({test_acc_lr*100:.2f}%)")
print(f"   F1-Score:       {f1_lr:.4f} ({f1_lr*100:.2f}%) ⭐")
print(f"   Precision:      {precision_lr:.4f} ({precision_lr*100:.2f}%)")
print(f"   Recall:         {recall_lr:.4f} ({recall_lr*100:.2f}%)")

print(f"\n📋 Classification Report:")
print(classification_report(y_test, y_pred_test_lr, target_names=le_target.classes_, zero_division=0))

cm_lr = confusion_matrix(y_test, y_pred_test_lr)
plt.figure(figsize=(12, 10))
sns.heatmap(cm_lr, annot=True, fmt='d', cmap='Blues',
            xticklabels=le_target.classes_, yticklabels=le_target.classes_)
plt.title(f'Confusion Matrix - Logistic Regression (Acc: {test_acc_lr*100:.1f}%)', fontsize=14, fontweight='bold')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

results['Logistic Regression'] = {
    'model': lr_model,
    'test_accuracy': test_acc_lr,
    'f1_weighted': f1_lr,
    'precision': precision_lr,
    'recall': recall_lr
}

print("\n" + "=" * 70)
print("MODEL 2: DECISION TREE")
print("=" * 70)

dt_model = DecisionTreeClassifier(
    random_state=42, max_depth=20, min_samples_split=10,
    min_samples_leaf=5, class_weight='balanced'
)
dt_model.fit(X_train_scaled, y_train)

y_pred_test_dt = dt_model.predict(X_test_scaled)

test_acc_dt = accuracy_score(y_test, y_pred_test_dt)
f1_dt = f1_score(y_test, y_pred_test_dt, average='weighted')
precision_dt = precision_score(y_test, y_pred_test_dt, average='weighted', zero_division=0)
recall_dt = recall_score(y_test, y_pred_test_dt, average='weighted')

print(f"\n📊 Performance:")
print(f"   Test Accuracy:  {test_acc_dt:.4f} ({test_acc_dt*100:.2f}%)")
print(f"   F1-Score:       {f1_dt:.4f} ({f1_dt*100:.2f}%) ⭐")
print(f"   Precision:      {precision_dt:.4f} ({precision_dt*100:.2f}%)")
print(f"   Recall:         {recall_dt:.4f} ({recall_dt*100:.2f}%)")

print(f"\n📋 Classification Report:")
print(classification_report(y_test, y_pred_test_dt, target_names=le_target.classes_, zero_division=0))

cm_dt = confusion_matrix(y_test, y_pred_test_dt)
plt.figure(figsize=(12, 10))
sns.heatmap(cm_dt, annot=True, fmt='d', cmap='Greens',
            xticklabels=le_target.classes_, yticklabels=le_target.classes_)
plt.title(f'Confusion Matrix - Decision Tree (Acc: {test_acc_dt*100:.1f}%)', fontsize=14, fontweight='bold')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

results['Decision Tree'] = {
    'model': dt_model,
    'test_accuracy': test_acc_dt,
    'f1_weighted': f1_dt,
    'precision': precision_dt,
    'recall': recall_dt
}

print("\n" + "=" * 70)
print("MODEL 3: RANDOM FOREST (OPTIMIZED)")
print("=" * 70)

rf_model = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    max_depth=25,
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight='balanced',
    n_jobs=-1
)
rf_model.fit(X_train_scaled, y_train)

y_pred_test_rf = rf_model.predict(X_test_scaled)

test_acc_rf = accuracy_score(y_test, y_pred_test_rf)
f1_rf = f1_score(y_test, y_pred_test_rf, average='weighted')
precision_rf = precision_score(y_test, y_pred_test_rf, average='weighted', zero_division=0)
recall_rf = recall_score(y_test, y_pred_test_rf, average='weighted')

print(f"\n📊 Performance:")
print(f"   Test Accuracy:  {test_acc_rf:.4f} ({test_acc_rf*100:.2f}%)")
print(f"   F1-Score:       {f1_rf:.4f} ({f1_rf*100:.2f}%) ⭐")
print(f"   Precision:      {precision_rf:.4f} ({precision_rf*100:.2f}%)")
print(f"   Recall:         {recall_rf:.4f} ({recall_rf*100:.2f}%)")

print(f"\n📋 Classification Report:")
print(classification_report(y_test, y_pred_test_rf, target_names=le_target.classes_, zero_division=0))

cm_rf = confusion_matrix(y_test, y_pred_test_rf)
plt.figure(figsize=(12, 10))
sns.heatmap(cm_rf, annot=True, fmt='d', cmap='Oranges',
            xticklabels=le_target.classes_, yticklabels=le_target.classes_)
plt.title(f'Confusion Matrix - Random Forest (Acc: {test_acc_rf*100:.1f}%)', fontsize=14, fontweight='bold')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

print(f"\n🎯 Feature Importance (Top 15):")
feature_importance_rf = pd.DataFrame({
    'Feature': feature_columns,
    'Importance': rf_model.feature_importances_
}).sort_values('Importance', ascending=False)
print(feature_importance_rf.head(15).to_string(index=False))

results['Random Forest'] = {
    'model': rf_model,
    'test_accuracy': test_acc_rf,
    'f1_weighted': f1_rf,
    'precision': precision_rf,
    'recall': recall_rf
}

print("\n" + "=" * 70)
print("MODEL 4: GRADIENT BOOSTING")
print("=" * 70)

gb_model = GradientBoostingClassifier(
    n_estimators=200,
    random_state=42,
    max_depth=10,
    learning_rate=0.1,
    min_samples_split=10,
    min_samples_leaf=4
)
gb_model.fit(X_train_scaled, y_train)

y_pred_test_gb = gb_model.predict(X_test_scaled)

test_acc_gb = accuracy_score(y_test, y_pred_test_gb)
f1_gb = f1_score(y_test, y_pred_test_gb, average='weighted')
precision_gb = precision_score(y_test, y_pred_test_gb, average='weighted', zero_division=0)
recall_gb = recall_score(y_test, y_pred_test_gb, average='weighted')

print(f"\n📊 Performance:")
print(f"   Test Accuracy:  {test_acc_gb:.4f} ({test_acc_gb*100:.2f}%)")
print(f"   F1-Score:       {f1_gb:.4f} ({f1_gb*100:.2f}%) ⭐")
print(f"   Precision:      {precision_gb:.4f} ({precision_gb*100:.2f}%)")
print(f"   Recall:         {recall_gb:.4f} ({recall_gb*100:.2f}%)")

print(f"\n📋 Classification Report:")
print(classification_report(y_test, y_pred_test_gb, target_names=le_target.classes_, zero_division=0))

cm_gb = confusion_matrix(y_test, y_pred_test_gb)
plt.figure(figsize=(12, 10))
sns.heatmap(cm_gb, annot=True, fmt='d', cmap='Purples',
            xticklabels=le_target.classes_, yticklabels=le_target.classes_)
plt.title(f'Confusion Matrix - Gradient Boosting (Acc: {test_acc_gb*100:.1f}%)', fontsize=14, fontweight='bold')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

results['Gradient Boosting'] = {
    'model': gb_model,
    'test_accuracy': test_acc_gb,
    'f1_weighted': f1_gb,
    'precision': precision_gb,
    'recall': recall_gb
}

print("\n" + "=" * 70)
print("MODEL COMPARISON - ALL RESULTS")
print("=" * 70)

# Create comparison DataFrame
comparison_df = pd.DataFrame({
    'Model': list(results.keys()),
    'Test Accuracy': [f"{results[m]['test_accuracy']*100:.2f}%" for m in results.keys()],
    'F1-Score': [f"{results[m]['f1_weighted']*100:.2f}%" for m in results.keys()],
    'Precision': [f"{results[m]['precision']*100:.2f}%" for m in results.keys()],
    'Recall': [f"{results[m]['recall']*100:.2f}%" for m in results.keys()]
})

print("\n" + comparison_df.to_string(index=False))

# Find best model
best_model_name = max(results, key=lambda x: results[x]['f1_weighted'])
best_model_obj = results[best_model_name]['model']

print("\n" + "=" * 70)
print(f"🏆 BEST MODEL: {best_model_name}")
print("=" * 70)
print(f"\nSelected based on F1-Score (Weighted) - Best for medical platforms!")
print(f"\n📈 Performance:")
print(f"   • Test Accuracy:  {results[best_model_name]['test_accuracy']*100:.2f}%")
print(f"   • F1-Score:       {results[best_model_name]['f1_weighted']*100:.2f}% ⭐")
print(f"   • Precision:      {results[best_model_name]['precision']*100:.2f}%")
print(f"   • Recall:         {results[best_model_name]['recall']*100:.2f}%")

# Quality assessment
f1 = results[best_model_name]['f1_weighted']
if f1 >= 0.85:
    print(f"\n✅ EXCELLENT - Ready for production!")
elif f1 >= 0.75:
    print(f"\n✅ GOOD - Suitable for medical use with monitoring")
elif f1 >= 0.65:
    print(f"\n⚠️  MODERATE - Consider collecting more data")
else:
    print(f"\n❌ NEEDS IMPROVEMENT - More data required")

# Visualize comparison
plt.figure(figsize=(12, 6))
models_list = list(results.keys())
f1_scores = [results[m]['f1_weighted'] * 100 for m in models_list]
test_accs = [results[m]['test_accuracy'] * 100 for m in models_list]

x = np.arange(len(models_list))
width = 0.35

plt.bar(x - width/2, test_accs, width, label='Test Accuracy', alpha=0.8)
plt.bar(x + width/2, f1_scores, width, label='F1-Score', alpha=0.8)

plt.xlabel('Models')
plt.ylabel('Score (%)')
plt.title('Model Performance Comparison')
plt.xticks(x, models_list, rotation=15, ha='right')
plt.legend()
plt.ylim(0, 100)
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

preventive_measures = {
    'Diabetes_Related': {
        'short_term': [
            'Monitor blood glucose levels daily',
            'Avoid sugary foods and refined carbohydrates',
            'Stay hydrated with water',
            'Take prescribed medications on time'
        ],
        'long_term': [
            'Follow a low-glycemic diet',
            'Exercise for 30 minutes, 5 days/week',
            'Maintain healthy body weight (BMI < 25)',
            'Regular HbA1c testing every 3 months'
        ],
        'lifestyle': [
            'Quit smoking',
            'Limit alcohol',
            'Manage stress',
            'Get 7-8 hours sleep'
        ]
    },
    'Kidney_Disease': {
        'short_term': [
            'Monitor creatinine levels monthly',
            'Stay hydrated (8-10 glasses water daily)',
            'Reduce salt intake (<5g/day)',
            'Avoid NSAIDs without approval'
        ],
        'long_term': [
            'Control blood pressure (<130/80)',
            'Manage diabetes if present',
            'Follow low-protein diet if recommended',
            'Regular kidney function tests'
        ],
        'lifestyle': [
            'Quit smoking',
            'Maintain healthy weight',
            'Regular exercise (walking, swimming)',
            'Limit processed foods'
        ]
    },
    'Cardiovascular_Disease': {
        'short_term': [
            'Monitor blood pressure twice daily',
            'Take heart medications as prescribed',
            'Limit sodium (<2g/day)',
            'Recognize warning signs (chest pain, SOB)'
        ],
        'long_term': [
            'Follow Mediterranean diet',
            'Exercise 30-45 min, 5 days/week',
            'Maintain healthy cholesterol',
            'Regular ECG and stress tests'
        ],
        'lifestyle': [
            'Stop smoking',
            'Limit alcohol',
            'Manage stress',
            'Maintain healthy weight'
        ]
    },
    'Infection': {
        'short_term': [
            'Complete antibiotic course',
            'Practice hand hygiene',
            'Get adequate rest',
            'Stay hydrated'
        ],
        'long_term': [
            'Strengthen immune system',
            'Keep vaccinations updated',
            'Regular health check-ups',
            'Treat chronic conditions'
        ],
        'lifestyle': [
            'Avoid sick contacts',
            'Good personal hygiene',
            'Eat immune-boosting foods',
            'Regular exercise'
        ]
    },
    'Respiratory_Disease': {
        'short_term': [
            'Use prescribed inhalers correctly',
            'Avoid air pollution and irritants',
            'Practice breathing exercises',
            'Monitor oxygen saturation'
        ],
        'long_term': [
            'Regular lung function tests',
            'Pulmonary rehabilitation',
            'Maintain healthy weight',
            'Annual flu and pneumonia vaccinations'
        ],
        'lifestyle': [
            'Quit smoking immediately',
            'Avoid secondhand smoke',
            'Use air purifiers at home',
            'Regular aerobic exercise'
        ]
    },
    'Liver_Disease': {
        'short_term': [
            'Avoid alcohol completely',
            'Monitor liver enzymes regularly',
            'Take prescribed medications',
            'Watch for worsening signs'
        ],
        'long_term': [
            'Hepatitis vaccinations (A and B)',
            'Low-fat, high-fiber diet',
            'Regular liver function tests',
            'Maintain healthy weight'
        ],
        'lifestyle': [
            'Absolutely no alcohol',
            'Avoid hepatotoxic medications',
            'Regular exercise',
            'Adequate protein intake'
        ]
    },
    'Other_Condition': {
        'short_term': [
            'Follow doctor\'s treatment plan',
            'Monitor symptoms daily',
            'Take medications as prescribed',
            'Attend follow-up appointments'
        ],
        'long_term': [
            'Regular health check-ups',
            'Maintain balanced diet',
            'Regular physical activity',
            'Preventive screenings'
        ],
        'lifestyle': [
            'Healthy lifestyle habits',
            'Stress management',
            'Adequate sleep',
            'Social support'
        ]
    }
}

risk_based_measures = {
    'High_Diabetes_Risk': [
        '⚠️ HIGH DIABETES RISK',
        'Schedule HbA1c test within 1 week',
        'Cut refined sugars immediately',
        'Start daily 30-minute walks'
    ],
    'High_Kidney_Risk': [
        '⚠️ KIDNEY DYSFUNCTION RISK',
        'Check creatinine and GFR within 3 days',
        'Reduce protein intake',
        'Monitor BP twice daily'
    ],
    'High_BP_Risk': [
        '⚠️ HYPERTENSION RISK',
        'Monitor BP twice daily',
        'Reduce sodium to <2g/day',
        'Start DASH diet'
    ],
    'Anemia_Risk': [
        '⚠️ ANEMIA DETECTED',
        'Increase iron-rich foods',
        'Vitamin C with meals',
        'Check iron, B12, folate levels'
    ]
}

print("✓ Preventive measures database created")

def predict_patient_risk(patient_data, model, scaler, le_target,
                        feature_columns, preventive_measures, risk_based_measures):
    """Predict disease risk and provide preventive measures"""

    # Prepare features
    X_patient = patient_data[feature_columns].copy()
    X_patient_scaled = scaler.transform(X_patient)

    # Predict
    prediction = model.predict(X_patient_scaled)[0]
    prediction_proba = model.predict_proba(X_patient_scaled)[0]

    # Get disease category
    predicted_disease = le_target.inverse_transform([prediction])[0]
    confidence = prediction_proba[prediction] * 100

    # Get top 3 risks
    top_3_indices = np.argsort(prediction_proba)[-3:][::-1]
    top_3_diseases = le_target.inverse_transform(top_3_indices)
    top_3_probas = prediction_proba[top_3_indices] * 100

    # Identify active risk factors
    active_risks = []
    if patient_data['Diabetes_Risk'].values[0] == 1:
        active_risks.extend(risk_based_measures.get('High_Diabetes_Risk', []))
    if patient_data['Kidney_Dysfunction_Risk'].values[0] == 1:
        active_risks.extend(risk_based_measures.get('High_Kidney_Risk', []))
    if patient_data['Hypertension_Risk'].values[0] == 1:
        active_risks.extend(risk_based_measures.get('High_BP_Risk', []))
    if patient_data['Anemia_Risk'].values[0] == 1:
        active_risks.extend(risk_based_measures.get('Anemia_Risk', []))

    # Get preventive measures
    disease_measures = preventive_measures.get(predicted_disease, preventive_measures.get('Other_Condition', {}))

    # Risk level
    risk_level = 'HIGH' if confidence > 70 else 'MODERATE' if confidence > 50 else 'LOW'
    timeline = '1-3 months' if confidence > 70 else '3-6 months' if confidence > 50 else '6-12 months'

    return {
        'disease': predicted_disease,
        'confidence': confidence,
        'risk_level': risk_level,
        'timeline': timeline,
        'top_risks': list(zip(top_3_diseases, top_3_probas)),
        'active_risks': active_risks,
        'preventive_measures': disease_measures
    }

print("✓ Prediction function created")

print("\n" + "=" * 70)
print("SAMPLE PATIENT PREDICTIONS")
print("=" * 70)

# Test on 3 random patients
for i in range(3):
    sample = X_test.iloc[[i]]

    result = predict_patient_risk(
        sample, best_model_obj, scaler, le_target,
        feature_columns, preventive_measures, risk_based_measures
    )

    print(f"\n{'='*70}")
    print(f"PATIENT #{i+1}")
    print(f"{'='*70}")
    print(f"\n🔮 Prediction: {result['disease']}")
    print(f"   Confidence: {result['confidence']:.1f}%")
    print(f"   Risk Level: {result['risk_level']}")
    print(f"   Timeline: {result['timeline']}")

    print(f"\n   Top 3 Risk Predictions:")
    for disease, prob in result['top_risks']:
        print(f"      {prob:5.1f}% - {disease}")

    if result['active_risks']:
        print(f"\n⚠️  Active Risk Factors:")
        for risk in result['active_risks'][:4]:
            print(f"   • {risk}")

    if result['preventive_measures']:
        print(f"\n💊 Recommended Preventive Measures:")
        print(f"\n   Short-term (Next 3 months):")
        for action in result['preventive_measures'].get('short_term', [])[:3]:
            print(f"   ✓ {action}")

        print(f"\n   Long-term (6-12 months):")
        for action in result['preventive_measures'].get('long_term', [])[:3]:
            print(f"   ✓ {action}")


# ====================================================================================
# CELL 16: Save Model for Production
# ====================================================================================
import pickle

# Save all components
with open('patient_risk_model.pkl', 'wb') as f:
    pickle.dump(best_model_obj, f)

with open('feature_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(le_target, f)

with open('feature_columns.pkl', 'wb') as f:
    pickle.dump(feature_columns, f)

with open('preventive_measures.pkl', 'wb') as f:
    pickle.dump(preventive_measures, f)

with open('risk_based_measures.pkl', 'wb') as f:
    pickle.dump(risk_based_measures, f)

print("✓ Model saved successfully!")
print("\nFiles created:")
print("  • patient_risk_model.pkl")
print("  • feature_scaler.pkl")
print("  • label_encoder.pkl")
print("  • feature_columns.pkl")
print("  • preventive_measures.pkl")
print("  • risk_based_measures.pkl")


# ====================================================================================
# CELL 17: Final Summary
# ====================================================================================
print("\n" + "=" * 70)
print("FINAL MODEL EVALUATION SUMMARY")
print("=" * 70)

print(f"\n✅ Best Model: {best_model_name}")
print(f"\n📈 Performance Metrics:")
print(f"   • Test Accuracy:  {results[best_model_name]['test_accuracy']:.2%}")
print(f"   • F1-Score:       {results[best_model_name]['f1_weighted']:.2%} ⭐")
print(f"   • Precision:      {results[best_model_name]['precision']:.2%}")
print(f"   • Recall:         {results[best_model_name]['recall']:.2%}")

print("\n📊 METRIC TO USE: F1-Score (Weighted)")
print("   This is the BEST metric for medical platforms!")
print("   It balances precision and recall")

f1 = results[best_model_name]['f1_weighted']
if f1 >= 0.85:
    print(f"\n✅ EXCELLENT ({f1:.1%}) - Ready for production!")
elif f1 >= 0.75:
    print(f"\n✅ GOOD ({f1:.1%}) - Suitable with monitoring")
elif f1 >= 0.65:
    print(f"\n⚠️  MODERATE ({f1:.1%}) - Needs improvement")
else:
    print(f"\n❌ NEEDS WORK ({f1:.1%}) - Collect more data")

print("\n" + "=" * 70)
print("✅ PATIENT RISK PREDICTION MODEL COMPLETE!")
print("=" * 70)

#######

from sklearn.model_selection import train_test_split

X_train_risk, X_test_risk, y_train_risk, y_test_risk = train_test_split(
    X, y_encoded, # Use y_encoded for numerical labels
    test_size=0.2,
    random_state=42,
    stratify=y_encoded # Stratify by y_encoded as well
)

print("Risk prediction data split into training and testing sets.")
print(f"X_train_risk shape: {X_train_risk.shape}, y_train_risk shape: {y_train_risk.shape}")
print(f"X_test_risk shape: {X_test_risk.shape}, y_test_risk shape: {y_test_risk.shape}")

from sklearn.linear_model import LogisticRegression

risk_logistic_model = LogisticRegression(
    max_iter=1000,
    class_weight="balanced",
    random_state=42
)

risk_logistic_model.fit(X_train_risk, y_train_risk)

print("Logistic Regression model for risk prediction trained.")

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

risk_logistic_preds = risk_logistic_model.predict(X_test_risk)

print("📊 Logistic Regression Classification Report (Risk Prediction):")
print(classification_report(y_test_risk, risk_logistic_preds, target_names=le_target.classes_))

cm_risk = confusion_matrix(y_test_risk, risk_logistic_preds, normalize="true")

plt.figure(figsize=(10, 8))
disp = ConfusionMatrixDisplay(confusion_matrix=cm_risk, display_labels=le_target.classes_)
disp.plot(cmap="Reds", xticks_rotation=45)
plt.title("Logistic Regression for Risk Prediction – Normalized Confusion Matrix")
plt.tight_layout()
plt.show()

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

rf_risk_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

rf_risk_model.fit(X_train_risk, y_train_risk)

rf_risk_preds = rf_risk_model.predict(X_test_risk)

print("📊 Random Forest Classification Report (Risk Prediction):")
print(classification_report(y_test_risk, rf_risk_preds))

cm_rf_risk = confusion_matrix(y_test_risk, rf_risk_preds, normalize="true")

plt.figure(figsize=(6, 6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm_rf_risk)
disp.plot(cmap="Greens")
plt.title("Random Forest for Risk Prediction – Normalized Confusion Matrix")
plt.show()

from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

xgb_risk_model = XGBClassifier(
    n_estimators=400,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='multi:softmax', # Changed to multi:softmax for multi-class classification
    num_class=len(le_target.classes_), # Explicitly set num_class
    eval_metric='mlogloss',       # Changed to mlogloss for multi-class evaluation
    random_state=42,
    use_label_encoder=False      # Suppress warning for label encoding
)

xgb_risk_model.fit(X_train_risk, y_train_risk)

xgb_risk_preds = xgb_risk_model.predict(X_test_risk)

print("📊 XGBoost Classification Report (Risk Prediction):")
print(classification_report(y_test_risk, xgb_risk_preds, target_names=le_target.classes_))

cm_xgb_risk = confusion_matrix(y_test_risk, xgb_risk_preds, normalize="true")

plt.figure(figsize=(10, 8)) # Increased figure size for better readability
disp = ConfusionMatrixDisplay(confusion_matrix=cm_xgb_risk, display_labels=le_target.classes_)
disp.plot(cmap="Purples", xticks_rotation=45)
plt.title("XGBoost for Risk Prediction – Normalized Confusion Matrix")
plt.tight_layout() # Adjust layout to prevent labels from overlapping
plt.show()

from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore', category=UserWarning)

lgbm_risk_model = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=7,
    class_weight="balanced",
    random_state=42
)

lgbm_risk_model.fit(X_train_risk, y_train_risk)

lgbm_risk_preds = lgbm_risk_model.predict(X_test_risk)

print("📊 LightGBM Classification Report (Risk Prediction):")
print(classification_report(y_test_risk, lgbm_risk_preds))

cm_lgbm_risk = confusion_matrix(y_test_risk, lgbm_risk_preds, normalize="true")

plt.figure(figsize=(6, 6))
disp = ConfusionMatrixDisplay(confusion_matrix=cm_lgbm_risk)
disp.plot(cmap="Blues")
plt.title("LightGBM for Risk Prediction – Normalized Confusion Matrix")
plt.show()

from sklearn.preprocessing import LabelEncoder

risk_encoders = {}

# Recalculate cat_cols_risk based on the current X
cat_cols_risk = X.select_dtypes(include='object').columns

for col in cat_cols_risk:
    le = LabelEncoder()
    X[col] = le.fit_transform(X[col])
    risk_encoders[col] = le

print("Categorical columns in X for risk prediction task have been Label Encoded.")

from sklearn.preprocessing import StandardScaler

risk_scaler = StandardScaler()
X[num_cols_risk] = risk_scaler.fit_transform(X[num_cols_risk])

print("Numerical columns in X for risk prediction task have been scaled using StandardScaler.")

from sklearn.model_selection import train_test_split

X_train_risk, X_test_risk, y_train_risk, y_test_risk = train_test_split(
    X, y_encoded, # Use y_encoded for numerical labels
    test_size=0.2,
    random_state=42,
    stratify=y_encoded # Stratify by y_encoded as well
)

print("Risk prediction data split into training and testing sets.")
print(f"X_train_risk shape: {X_train_risk.shape}, y_train_risk shape: {y_train_risk.shape}")
print(f"X_test_risk shape: {X_test_risk.shape}, y_test_risk shape: {y_test_risk.shape}")

print("Class distribution of y_train_risk:")
print(pd.Series(y_train_risk).value_counts())

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train_risk, y_train_risk)

print("Class distribution after SMOTE:")
print(pd.Series(y_resampled).value_counts())

#may dleye the tuned and the diagnosis model

# from sklearn.model_selection import RandomizedSearchCV
# from xgboost import XGBClassifier # Ensure XGBClassifier is imported

# # Define parameter distribution for XGBoost
# param_dist = {
#     'n_estimators': [100, 200, 300, 400, 500],
#     'max_depth': [3, 4, 5, 6, 7, 8],
#     'learning_rate': [0.01, 0.05, 0.1, 0.2],
#     'subsample': [0.6, 0.7, 0.8, 0.9, 1.0],
#     'colsample_bytree': [0.6, 0.7, 0.8, 0.9, 1.0]
# }

# # Initialize XGBoost Classifier with multi-class objective
# xgb_base_model = XGBClassifier(
#     objective='multi:softmax',
#     num_class=len(le_target.classes_),
#     eval_metric='mlogloss',
#     random_state=42,
#     use_label_encoder=False
# )

# # Instantiate RandomizedSearchCV
# random_search_xgb = RandomizedSearchCV(
#     estimator=xgb_base_model,
#     param_distributions=param_dist,
#     n_iter=50, # Number of parameter settings that are sampled
#     cv=5,       # 5-fold cross-validation
#     scoring='f1_macro', # Use f1_macro for multi-class classification
#     random_state=42,
#     n_jobs=-1,  # Use all available cores
#     verbose=1
# )

# # Fit RandomizedSearchCV to the SMOTE-resampled training data
# random_search_xgb.fit(X_resampled, y_resampled)

# # Print the best parameters
# print("Best parameters found by RandomizedSearchCV for XGBoost:")
# print(random_search_xgb.best_params_)

# from xgboost import XGBClassifier
# from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
# import matplotlib.pyplot as plt

# # Instantiate XGBoost model with best parameters
# best_xgb_risk_model = XGBClassifier(
#     objective='binary:logistic',
#     eval_metric='logloss',
#     random_state=42,
#     **random_search_xgb.best_params_
# )

# # Train the model on the resampled training data
# best_xgb_risk_model.fit(X_resampled, y_resampled)

# # Make predictions on the original test set
# best_xgb_risk_preds = best_xgb_risk_model.predict(X_test_risk)

# # Print classification report
# print("📊 Tuned XGBoost Classification Report (Risk Prediction):")
# print(classification_report(y_test_risk, best_xgb_risk_preds))

# # Plot confusion matrix
# cm_best_xgb_risk = confusion_matrix(y_test_risk, best_xgb_risk_preds, normalize="true")

# plt.figure(figsize=(6, 6))
# disp = ConfusionMatrixDisplay(confusion_matrix=cm_best_xgb_risk)
# disp.plot(cmap="Purples")
# plt.title("Tuned XGBoost for Risk Prediction – Normalized Confusion Matrix")
# plt.show()

# from xgboost import XGBClassifier
# from sklearn.metrics import classification_report
# import numpy as np # Import numpy to get unique classes

# # Print unique classes in y_train for debugging
# print(f"Unique classes in y_train: {np.unique(y_train)}")
# print(f"Number of unique classes in y_train: {len(np.unique(y_train))}")

# xgb_model = XGBClassifier(
#     n_estimators=400,
#     max_depth=6,
#     learning_rate=0.05,
#     subsample=0.8,
#     colsample_bytree=0.8,
#     objective="multi:softmax",
#     num_class=len(np.unique(y_train)), # Explicitly set num_class
#     eval_metric="mlogloss",
#     random_state=42
# )

# xgb_model.fit(X_train, y_train)

# xgb_preds = xgb_model.predict(X_test)

# print("📊 XGBoost Classification Report (Diagnosis Task):")
# print(classification_report(y_test, xgb_preds))